local M = {}
M.name = "Monthly Review"

function M.run(e, p)
  local date = e.today()
  local date_long = e.today_long()
  local month_start = e.date_offset(-30)

  local year = date:sub(1, 4)
  local month = date:sub(6, 7)
  local month_name = date_long:match("^(%a+)")

  local default_title = month_name .. " " .. year .. " Review"
  local title = e.input({ prompt = "Month title", default = default_title })
  if not title or title == "" then return end

  local content = "---\n"
    .. "type: log\n"
    .. "subtype: monthly-review\n"
    .. "month_of: " .. year .. "-" .. month .. "\n"
    .. "tags:\n"
    .. "  - log\n"
    .. "  - monthly-review\n"
    .. "---\n\n"
    .. "# " .. title .. " \xE2\x80\x94 " .. date_long .. "\n\n"
    .. "---\n\n"
    .. "## Monthly Summary\n\n"
    .. "> [!note] High-level summary of the month\n\n"
    .. "-\n\n"
    .. "## Weekly Reviews This Month\n\n"
    .. "```dataview\n"
    .. "LIST\n"
    .. "FROM \"Log\"\n"
    .. "WHERE subtype = \"weekly-review\"\n"
    .. "WHERE date(week_of) >= date(\"" .. month_start .. "\") AND date(week_of) <= date(\"" .. date .. "\")\n"
    .. "SORT file.name ASC\n"
    .. "```\n\n"
    .. "---\n\n"
    .. "## Research Accomplishments\n\n"
    .. "> [!tip] Major research milestones, papers, experiments, and breakthroughs\n\n"
    .. "-\n\n"
    .. "## Personal / Life Accomplishments\n\n"
    .. "> [!tip] Personal wins, habits built, life improvements\n\n"
    .. "-\n\n"
    .. "## Project Progress\n\n"
    .. "```dataview\n"
    .. "TABLE WITHOUT ID\n"
    .. "  link(file.link, file.name) AS \"Project\",\n"
    .. "  status AS \"Status\",\n"
    .. "  category AS \"Category\"\n"
    .. "FROM \"Projects\"\n"
    .. "WHERE type = \"project\" AND status != \"Complete\" AND status != \"Cancelled\"\n"
    .. "SORT status ASC, file.name ASC\n"
    .. "```\n\n"
    .. "| Project | Progress This Month | Next Steps |\n"
    .. "| ------- | ------------------- | ---------- |\n"
    .. "| [[]]    |                     |            |\n\n"
    .. "## Areas Health Check\n\n"
    .. "> [!check] Monthly health check on each life area\n\n"
    .. "| Area | Status | Trend | Action Needed? |\n"
    .. "| ---- | ------ | ----- | -------------- |\n"
    .. "| [[Finance]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 | \xE2\x86\x91 / \xE2\x86\x92 / \xE2\x86\x93 |  |\n"
    .. "| [[Health & Fitness]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 | \xE2\x86\x91 / \xE2\x86\x92 / \xE2\x86\x93 |  |\n"
    .. "| [[Vehicles]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 | \xE2\x86\x91 / \xE2\x86\x92 / \xE2\x86\x93 |  |\n"
    .. "| [[Home]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 | \xE2\x86\x91 / \xE2\x86\x92 / \xE2\x86\x93 |  |\n"
    .. "| [[Career]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 | \xE2\x86\x91 / \xE2\x86\x92 / \xE2\x86\x93 |  |\n\n"
    .. "## Tasks Completed This Month\n\n"
    .. "```dataviewjs\n"
    .. "const monthStart = dv.date(\"" .. month_start .. "\");\n"
    .. "const rows = [];\n"
    .. "const clean = t => t\n"
    .. "  .replace(/\\*{0,2}\\[\\w+::[^\\]]*\\]\\*{0,2}/g, \"\")\n"
    .. "  .replace(/\\[\\[(?:[^\\]|]*\\|)?([^\\]]*)\\]\\]/g, \"$1\")\n"
    .. "  .replace(/^\\s*(?::\\s*)+/, \"\").replace(/(?:\\s*:)+\\s*$/, \"\").trim();\n"
    .. "\n"
    .. "for (const p of dv.pages('\"Projects\" OR \"Areas\"'))\n"
    .. "  for (const t of p.file.tasks.where(t => t.completed && t.completion && t.completion >= monthStart))\n"
    .. "    rows.push([dv.fileLink(p.file.path, false, clean(t.text) || t.text), t.completion]);\n"
    .. "\n"
    .. "for (const n of dv.pages('\"Projects\"').where(p => p.type === \"task\" && p.status === \"Complete\" && p.date_completed && dv.date(p.date_completed) >= monthStart))\n"
    .. "  rows.push([dv.fileLink(n.file.path, false, n.file.name), n.date_completed]);\n"
    .. "\n"
    .. "rows.sort((a, b) => b[1] < a[1] ? -1 : b[1] > a[1] ? 1 : 0);\n"
    .. "if (rows.length > 0) dv.table([\"Task\", \"Completed\"], rows);\n"
    .. "else dv.paragraph(\"No tasks completed this month.\");\n"
    .. "```\n\n"
    .. "## Key Decisions & Insights\n\n"
    .. "> [!info] Significant decisions made and insights gained this month\n\n"
    .. "-\n\n"
    .. "## What Worked\n\n"
    .. "> [!tip] Processes, habits, or approaches that paid off\n\n"
    .. "-\n\n"
    .. "## What Didn't Work\n\n"
    .. "> [!warning] Blockers, dead ends, or wasted effort \xE2\x80\x94 and what to change\n\n"
    .. "-\n\n"
    .. "## Goals for Next Month\n\n"
    .. "### Research\n"
    .. "1.\n\n"
    .. "### Personal\n"
    .. "1.\n\n"
    .. "### Life Admin\n"
    .. "1.\n\n"
    .. "## Notes\n"

  e.write_note("Log/" .. title, content)
end

return M
