local M = {}
M.name = "Quarterly Review"

function M.run(e, p)
  local date = e.today()
  local date_long = e.today_long()
  local quarter_start = e.date_offset(-90)

  local year = date:sub(1, 4)
  local month = tonumber(date:sub(6, 7))
  local quarter = math.ceil(month / 3)

  local default_title = "Q" .. quarter .. " " .. year .. " Review"
  local title = e.input({ prompt = "Quarter title", default = default_title })
  if not title or title == "" then return end

  local content = "---\n"
    .. "type: log\n"
    .. "subtype: quarterly-review\n"
    .. "quarter_of: " .. year .. "-Q" .. quarter .. "\n"
    .. "tags:\n"
    .. "  - log\n"
    .. "  - quarterly-review\n"
    .. "---\n\n"
    .. "# " .. title .. " \xE2\x80\x94 " .. date_long .. "\n\n"
    .. "---\n\n"
    .. "## Quarter Overview\n\n"
    .. "> [!note] High-level narrative of the quarter\n\n"
    .. "-\n\n"
    .. "## Monthly Reviews This Quarter\n\n"
    .. "```dataview\n"
    .. "LIST\n"
    .. "FROM \"Log\"\n"
    .. "WHERE subtype = \"monthly-review\"\n"
    .. "WHERE date(month_of) >= date(\"" .. quarter_start .. "\") AND date(month_of) <= date(\"" .. date .. "\")\n"
    .. "SORT file.name ASC\n"
    .. "```\n\n"
    .. "---\n\n"
    .. "## Strategic Assessment\n\n"
    .. "> [!info] Are you heading in the right direction? What needs to shift?\n\n"
    .. "-\n\n"
    .. "## Project Status Summary\n\n"
    .. "```dataview\n"
    .. "TABLE WITHOUT ID\n"
    .. "  link(file.link, file.name) AS \"Project\",\n"
    .. "  status AS \"Status\",\n"
    .. "  category AS \"Category\",\n"
    .. "  date_created AS \"Started\"\n"
    .. "FROM \"Projects\"\n"
    .. "WHERE type = \"project\"\n"
    .. "SORT status ASC, file.name ASC\n"
    .. "```\n\n"
    .. "## OKR / Goal Progress\n\n"
    .. "> [!check] Rate progress on each goal: 1 (no progress) to 5 (exceeded)\n\n"
    .. "| Goal | Rating (1-5) | Evidence | Notes |\n"
    .. "| ---- | ------------ | -------- | ----- |\n"
    .. "|      |              |          |       |\n\n"
    .. "## Areas Deep Dive\n\n"
    .. "### Finance\n\n"
    .. "- **Status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Quarter trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next quarter focus:**\n\n"
    .. "### Health & Fitness\n\n"
    .. "- **Status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Quarter trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next quarter focus:**\n\n"
    .. "### Vehicles\n\n"
    .. "- **Status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Quarter trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next quarter focus:**\n\n"
    .. "### Home\n\n"
    .. "- **Status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Quarter trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next quarter focus:**\n\n"
    .. "### Career\n\n"
    .. "- **Status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Quarter trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next quarter focus:**\n\n"
    .. "## Key Wins\n\n"
    .. "> [!tip] The biggest accomplishments of the quarter\n\n"
    .. "1.\n"
    .. "2.\n"
    .. "3.\n\n"
    .. "## Key Challenges\n\n"
    .. "> [!warning] Biggest obstacles, setbacks, or frustrations\n\n"
    .. "1.\n"
    .. "2.\n"
    .. "3.\n\n"
    .. "## Lessons Learned\n\n"
    .. "> [!info] What did this quarter teach you?\n\n"
    .. "-\n\n"
    .. "## Next Quarter Priorities\n\n"
    .. "### Research\n"
    .. "1.\n\n"
    .. "### Personal\n"
    .. "1.\n\n"
    .. "### Life Admin\n"
    .. "1.\n\n"
    .. "## Notes\n"

  e.write_note("Log/" .. title, content)
end

return M
