local M = {}
M.name = "Weekly Review"

function M.run(e, p)
  local date = e.today()
  local date_long = e.today_long()
  local week_num = e.week_number()
  local week_ago = e.date_offset(-6)

  local default_title = "Week " .. week_num .. " Review"
  local title = e.input({ prompt = "Week title", default = default_title })
  if not title or title == "" then return end

  local content = "---\n"
    .. "type: log\n"
    .. "subtype: weekly-review\n"
    .. "week_of: " .. date .. "\n"
    .. "week_number: " .. week_num .. "\n"
    .. "tags:\n"
    .. "  - log\n"
    .. "  - weekly-review\n"
    .. "---\n\n"
    .. "# " .. title .. " \xE2\x80\x94 " .. date_long .. "\n\n"
    .. "---\n\n"
    .. "## This Week's Log Entries\n\n"
    .. "```dataview\n"
    .. "LIST\n"
    .. "FROM \"Log\"\n"
    .. "WHERE type = \"log\" AND !contains(tags, \"weekly-review\")\n"
    .. "WHERE date >= date(\"" .. week_ago .. "\") AND date <= date(\"" .. date .. "\")\n"
    .. "SORT date ASC\n"
    .. "```\n\n"
    .. "---\n\n"
    .. "## Research Accomplishments\n\n"
    .. "-\n\n"
    .. "## Personal / Life Accomplishments\n\n"
    .. "-\n\n"
    .. "## Progress by Project\n\n"
    .. "| Project | Category | What Moved Forward | What Stalled |\n"
    .. "| ------- | -------- | ------------------ | ------------ |\n"
    .. "| [[]]    |          |                    |              |\n\n"
    .. "## Areas Check-In\n\n"
    .. "> [!check] Quick health check on each life area\n\n"
    .. "| Area | Status | Action Needed? |\n"
    .. "| ---- | ------ | -------------- |\n"
    .. "| [[Finance]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 |  |\n"
    .. "| [[Health & Fitness]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 |  |\n"
    .. "| [[Vehicles]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 |  |\n"
    .. "| [[Home]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 |  |\n"
    .. "| [[Career]] | \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4 |  |\n\n"
    .. "## Tasks Completed This Week\n\n"
    .. "```dataviewjs\n"
    .. "const weekStart = dv.date(\"" .. week_ago .. "\");\n"
    .. "const rows = [];\n"
    .. "const clean = t => t\n"
    .. "  .replace(/\\*{0,2}\\[\\w+::[^\\]]*\\]\\*{0,2}/g, \"\")\n"
    .. "  .replace(/\\[\\[(?:[^\\]|]*\\|)?([^\\]]*)\\]\\]/g, \"$1\")\n"
    .. "  .replace(/^\\s*(?::\\s*)+/, \"\").replace(/(?:\\s*:)+\\s*$/, \"\").trim();\n"
    .. "\n"
    .. "for (const p of dv.pages('\"Projects\" OR \"Areas\"'))\n"
    .. "  for (const t of p.file.tasks.where(t => t.completed && t.completion && t.completion >= weekStart))\n"
    .. "    rows.push([dv.fileLink(p.file.path, false, clean(t.text) || t.text), t.completion]);\n"
    .. "\n"
    .. "for (const n of dv.pages('\"Projects\"').where(p => p.type === \"task\" && p.status === \"Complete\" && p.date_completed && dv.date(p.date_completed) >= weekStart))\n"
    .. "  rows.push([dv.fileLink(n.file.path, false, n.file.name), n.date_completed]);\n"
    .. "\n"
    .. "rows.sort((a, b) => b[1] < a[1] ? -1 : b[1] > a[1] ? 1 : 0);\n"
    .. "if (rows.length > 0) dv.table([\"Task\", \"Completed\"], rows);\n"
    .. "else dv.paragraph(\"No tasks completed this week.\");\n"
    .. "```\n\n"
    .. "## Overdue Tasks\n\n"
    .. "```dataviewjs\n"
    .. "const today = dv.date(\"today\");\n"
    .. "const rows = [];\n"
    .. "const clean = t => t\n"
    .. "  .replace(/\\*{0,2}\\[\\w+::[^\\]]*\\]\\*{0,2}/g, \"\")\n"
    .. "  .replace(/\\[\\[(?:[^\\]|]*\\|)?([^\\]]*)\\]\\]/g, \"$1\")\n"
    .. "  .replace(/^\\s*(?::\\s*)+/, \"\").replace(/(?:\\s*:)+\\s*$/, \"\").trim();\n"
    .. "\n"
    .. "for (const p of dv.pages('\"Projects\" OR \"Areas\"'))\n"
    .. "  for (const t of p.file.tasks.where(t => !t.completed && t.due && t.priority && t.due < today))\n"
    .. "    rows.push([dv.fileLink(p.file.path, false, clean(t.text) || t.text), t.due, t.priority, \"Open\"]);\n"
    .. "\n"
    .. "for (const n of dv.pages('\"Projects\"').where(p => p.type === \"task\" && p.status !== \"Complete\" && p.status !== \"Cancelled\" && p.due && p.priority && p.due < today))\n"
    .. "  rows.push([dv.fileLink(n.file.path, false, n.file.name), n.due, n.priority, n.status || \"\xE2\x80\x94\"]);\n"
    .. "\n"
    .. "rows.sort((a, b) => a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : 0);\n"
    .. "if (rows.length > 0) dv.table([\"Task\", \"Due\", \"Priority\", \"Status\"], rows);\n"
    .. "else dv.paragraph(\"No overdue tasks.\");\n"
    .. "```\n\n"
    .. "## Overdue Recurring Tasks\n\n"
    .. "```dataview\n"
    .. "TABLE WITHOUT ID\n"
    .. "  link(file.link, file.name) AS \"Task\",\n"
    .. "  area AS \"Area\",\n"
    .. "  next_due AS \"Due\"\n"
    .. "FROM \"Areas\"\n"
    .. "WHERE type = \"recurring-task\" AND next_due <= date(today)\n"
    .. "SORT next_due ASC\n"
    .. "```\n\n"
    .. "## Key Insights\n\n"
    .. "> [!tip] Ideas, patterns, or connections that emerged this week\n\n"
    .. "-\n\n"
    .. "> **Promotion check:** Should any of these become a concept note in `Domains/`?\n\n"
    .. "## Decisions Made\n\n"
    .. "> [!info] Significant choices and their reasoning\n\n"
    .. "-\n\n"
    .. "## What Didn't Work\n\n"
    .. "> [!warning] Blockers, dead ends, or wasted effort \xE2\x80\x94 and what to do differently\n\n"
    .. "-\n\n"
    .. "## Vault Maintenance\n\n"
    .. "- [ ] Process any items in Home quick capture inbox\n"
    .. "- [ ] Review stale project warnings on Home dashboard\n"
    .. "- [ ] Promote any reusable notes out of project folders\n"
    .. "- [ ] Update methodology notes if methods evolved this week\n"
    .. "- [ ] File any loose literature notes into Library\n"
    .. "- [ ] Update `next_due` on any completed recurring tasks\n"
    .. "- [ ] Review any areas due for their periodic review (check `review_frequency`)\n\n"
    .. "## Training This Week\n\n"
    .. "> Quick summary of training load and how the body is feeling\n\n"
    .. "-\n\n"
    .. "## Next Week's Priorities\n\n"
    .. "### Research\n"
    .. "1.\n\n"
    .. "### Personal\n"
    .. "1.\n\n"
    .. "### Life Admin\n"
    .. "1.\n\n"
    .. "## Notes\n"

  e.write_note("Log/" .. title, content)
end

return M
