local M = {}
M.name = "Yearly Review"

function M.run(e, p)
  local date = e.today()
  local date_long = e.today_long()

  local year = date:sub(1, 4)

  local default_title = year .. " Year in Review"
  local title = e.input({ prompt = "Year title", default = default_title })
  if not title or title == "" then return end

  local content = "---\n"
    .. "type: log\n"
    .. "subtype: yearly-review\n"
    .. "year: " .. year .. "\n"
    .. "tags:\n"
    .. "  - log\n"
    .. "  - yearly-review\n"
    .. "---\n\n"
    .. "# " .. title .. " \xE2\x80\x94 " .. date_long .. "\n\n"
    .. "---\n\n"
    .. "## Year Overview\n\n"
    .. "> [!note] The year in one paragraph\n\n"
    .. "-\n\n"
    .. "## Quarterly Reviews\n\n"
    .. "```dataview\n"
    .. "LIST\n"
    .. "FROM \"Log\"\n"
    .. "WHERE subtype = \"quarterly-review\"\n"
    .. "WHERE contains(quarter_of, \"" .. year .. "\")\n"
    .. "SORT file.name ASC\n"
    .. "```\n\n"
    .. "---\n\n"
    .. "## Major Accomplishments\n\n"
    .. "### Research\n\n"
    .. "> [!tip] Papers, grants, experiments, discoveries, milestones\n\n"
    .. "1.\n\n"
    .. "### Personal\n\n"
    .. "> [!tip] Skills, relationships, habits, growth\n\n"
    .. "1.\n\n"
    .. "### Life\n\n"
    .. "> [!tip] Major life events, purchases, moves, milestones\n\n"
    .. "1.\n\n"
    .. "## Projects Completed This Year\n\n"
    .. "```dataview\n"
    .. "TABLE WITHOUT ID\n"
    .. "  link(file.link, file.name) AS \"Project\",\n"
    .. "  category AS \"Category\",\n"
    .. "  date_completed AS \"Completed\"\n"
    .. "FROM \"Projects\"\n"
    .. "WHERE type = \"project\" AND status = \"Complete\"\n"
    .. "WHERE date_completed AND date(date_completed) >= date(\"" .. year .. "-01-01\") AND date(date_completed) <= date(\"" .. year .. "-12-31\")\n"
    .. "SORT date_completed ASC\n"
    .. "```\n\n"
    .. "## Projects Started / In Progress\n\n"
    .. "```dataview\n"
    .. "TABLE WITHOUT ID\n"
    .. "  link(file.link, file.name) AS \"Project\",\n"
    .. "  status AS \"Status\",\n"
    .. "  category AS \"Category\",\n"
    .. "  date_created AS \"Started\"\n"
    .. "FROM \"Projects\"\n"
    .. "WHERE type = \"project\" AND status != \"Complete\" AND status != \"Cancelled\"\n"
    .. "WHERE date_created AND date(date_created) >= date(\"" .. year .. "-01-01\")\n"
    .. "SORT status ASC, file.name ASC\n"
    .. "```\n\n"
    .. "## Areas Annual Assessment\n\n"
    .. "### Finance\n\n"
    .. "- **Year-end status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Year-over-year trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next year focus:**\n\n"
    .. "### Health & Fitness\n\n"
    .. "- **Year-end status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Year-over-year trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next year focus:**\n\n"
    .. "### Vehicles\n\n"
    .. "- **Year-end status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Year-over-year trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next year focus:**\n\n"
    .. "### Home\n\n"
    .. "- **Year-end status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Year-over-year trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next year focus:**\n\n"
    .. "### Career\n\n"
    .. "- **Year-end status:** \xF0\x9F\x9F\xA2 / \xF0\x9F\x9F\xA1 / \xF0\x9F\x94\xB4\n"
    .. "- **Year-over-year trend:**\n"
    .. "- **Key events:**\n"
    .. "- **Next year focus:**\n\n"
    .. "## Biggest Lessons\n\n"
    .. "> [!info] What did this year teach you?\n\n"
    .. "1.\n"
    .. "2.\n"
    .. "3.\n\n"
    .. "## Biggest Surprises\n\n"
    .. "> [!info] What caught you off guard \xE2\x80\x94 for better or worse?\n\n"
    .. "1.\n"
    .. "2.\n"
    .. "3.\n\n"
    .. "## What I'd Do Differently\n\n"
    .. "> [!warning] Hindsight is 20/20 \xE2\x80\x94 what would you change?\n\n"
    .. "-\n\n"
    .. "## Theme / Word for Next Year\n\n"
    .. "> [!target] A single word or phrase to anchor the year ahead\n\n"
    .. "-\n\n"
    .. "## Goals for Next Year\n\n"
    .. "### Research\n"
    .. "1.\n\n"
    .. "### Personal\n"
    .. "1.\n\n"
    .. "### Life Admin\n"
    .. "1.\n\n"
    .. "## Notes\n"

  e.write_note("Log/" .. title, content)
end

return M
