-- =============================================================================
-- LaTeX math command table (data only)
-- =============================================================================
-- Consumed by andrew.latex.blink-source, which turns each entry into a
-- blink.cmp completion item. This file holds NO logic: it returns a plain
-- array of entry tables.
--
-- Entry fields
--   cmd      string  REQUIRED. Command name WITHOUT the leading backslash
--                    ("alpha", "frac", "mathbb"). For environments, the
--                    environment name ("cases", "pmatrix"). Unique in this file.
--   kind     string  REQUIRED. One of: greek, letterlike, operator, bigop,
--                    relation, arrow, delimiter, accent, function, structure,
--                    font, spacing, environment, misc.
--   glyph    string  optional. The Unicode rendering, when one exists. Omitted
--                    for things with no single-glyph form (frac, sqrt, mathbb,
--                    environments, spacing, left/right pairs).
--   body     string  optional. LSP-snippet insert text INCLUDING the leading
--                    backslash, with $1/$2/$0 tab stops. Present only for
--                    commands that are useless without their braces.
--   label    string  optional. Display override; defaults to "\\" .. cmd.
--   aliases  string[] optional. Extra *search* words that are not themselves
--                    LaTeX commands ("fraction", "infinity", "piecewise").
--                    Real alternate spellings (\le, \ne, \wedge, ...) get their
--                    own entries instead.
--   doc      string  optional. One short line for the documentation window.
--                    Names the package whenever it is not core LaTeX. The
--                    preamble snacks.nvim renders with loads amsmath, amssymb,
--                    amsfonts, amscd and mathtools -- nothing here needs more.
--
-- Why the big operators have no `body`
--   This config's LuaSnip autosnippets already expand bare `sum` -> \sum_{i=1}^{n},
--   `int` -> \int_{a}^{b}, etc. If the completion source also inserted limits
--   the two would double up, so \sum, \prod, \int, \lim, \sin ... stay PLAIN
--   symbols here (body = nil) and the autosnippets keep ownership of limits.
--
-- Body escaping convention (verified against Neovim 0.12 `vim.snippet`, which
-- follows the LSP snippet grammar: a backslash escapes only `$`, `}` and `\`;
-- any other `\x` is passed through verbatim, backslash included)
--   * `\frac`, `\begin`, `\left`, `\{`  -> ONE Lua-escaped backslash:
--       "\\frac{$1}{$2}"      expands to  \frac{}{}
--       "\\left\\{$1..."      expands to  \left\{...
--   * a literal `\}` must protect the brace from the grammar, so it needs TWO
--     backslashes in the snippet text = FOUR in the Lua literal:
--       "\\right\\\\}$0"      expands to  \right\}
--   * a LaTeX line break `\\` likewise needs FOUR backslashes in the Lua
--     literal (`\\\\` in snippet text collapses to `\\`):
--       "$1 & $2 \\\\\\\\\n" expands to  $1 & $2 \\
--   * bare `$1` tab stops need no brace escaping, so `{` and `}` used as plain
--     LaTeX group braces stay unescaped.
-- =============================================================================

return {
  -- kind: greek ------------------------------------------------------------
  { cmd = "alpha", kind = "greek", glyph = "α", doc = "Greek small letter alpha" },
  { cmd = "beta", kind = "greek", glyph = "β", doc = "Greek small letter beta" },
  { cmd = "gamma", kind = "greek", glyph = "γ", doc = "Greek small letter gamma" },
  { cmd = "delta", kind = "greek", glyph = "δ", doc = "Greek small letter delta" },
  { cmd = "epsilon", kind = "greek", glyph = "ϵ", doc = "Greek lunate epsilon (U+03F5)" },
  { cmd = "varepsilon", kind = "greek", glyph = "ε", doc = "Greek small letter epsilon (U+03B5)" },
  { cmd = "zeta", kind = "greek", glyph = "ζ", doc = "Greek small letter zeta" },
  { cmd = "eta", kind = "greek", glyph = "η", doc = "Greek small letter eta" },
  { cmd = "theta", kind = "greek", glyph = "θ", doc = "Greek small letter theta" },
  { cmd = "vartheta", kind = "greek", glyph = "ϑ", doc = "Greek theta symbol (script variant)" },
  { cmd = "iota", kind = "greek", glyph = "ι", doc = "Greek small letter iota" },
  { cmd = "kappa", kind = "greek", glyph = "κ", doc = "Greek small letter kappa" },
  { cmd = "varkappa", kind = "greek", glyph = "ϰ", doc = "amssymb: Greek kappa symbol" },
  { cmd = "lambda", kind = "greek", glyph = "λ", doc = "Greek small letter lambda" },
  { cmd = "mu", kind = "greek", glyph = "μ", doc = "Greek small letter mu" },
  { cmd = "nu", kind = "greek", glyph = "ν", doc = "Greek small letter nu" },
  { cmd = "xi", kind = "greek", glyph = "ξ", doc = "Greek small letter xi" },
  { cmd = "pi", kind = "greek", glyph = "π", doc = "Greek small letter pi" },
  { cmd = "varpi", kind = "greek", glyph = "ϖ", doc = "Greek pi symbol (variant)" },
  { cmd = "rho", kind = "greek", glyph = "ρ", doc = "Greek small letter rho" },
  { cmd = "varrho", kind = "greek", glyph = "ϱ", doc = "Greek rho symbol (variant)" },
  { cmd = "sigma", kind = "greek", glyph = "σ", doc = "Greek small letter sigma" },
  { cmd = "varsigma", kind = "greek", glyph = "ς", doc = "Greek small final sigma" },
  { cmd = "tau", kind = "greek", glyph = "τ", doc = "Greek small letter tau" },
  { cmd = "upsilon", kind = "greek", glyph = "υ", doc = "Greek small letter upsilon" },
  { cmd = "phi", kind = "greek", glyph = "ϕ", doc = "Greek phi symbol (U+03D5, loopy)" },
  { cmd = "varphi", kind = "greek", glyph = "φ", doc = "Greek small letter phi (U+03C6)" },
  { cmd = "chi", kind = "greek", glyph = "χ", doc = "Greek small letter chi" },
  { cmd = "psi", kind = "greek", glyph = "ψ", doc = "Greek small letter psi" },
  { cmd = "omega", kind = "greek", glyph = "ω", doc = "Greek small letter omega" },
  { cmd = "digamma", kind = "greek", glyph = "ϝ", doc = "amssymb: Greek small letter digamma" },
  { cmd = "Gamma", kind = "greek", glyph = "Γ", doc = "Greek capital letter gamma" },
  { cmd = "Delta", kind = "greek", glyph = "Δ", doc = "Greek capital letter delta" },
  { cmd = "Theta", kind = "greek", glyph = "Θ", doc = "Greek capital letter theta" },
  { cmd = "Lambda", kind = "greek", glyph = "Λ", doc = "Greek capital letter lambda" },
  { cmd = "Xi", kind = "greek", glyph = "Ξ", doc = "Greek capital letter xi" },
  { cmd = "Pi", kind = "greek", glyph = "Π", doc = "Greek capital letter pi" },
  { cmd = "Sigma", kind = "greek", glyph = "Σ", doc = "Greek capital letter sigma" },
  { cmd = "Upsilon", kind = "greek", glyph = "Υ", doc = "Greek capital letter upsilon" },
  { cmd = "Phi", kind = "greek", glyph = "Φ", doc = "Greek capital letter phi" },
  { cmd = "Psi", kind = "greek", glyph = "Ψ", doc = "Greek capital letter psi" },
  { cmd = "Omega", kind = "greek", glyph = "Ω", doc = "Greek capital letter omega" },
  { cmd = "varGamma", kind = "greek", glyph = "Γ", doc = "amsmath, italic capital gamma" },
  { cmd = "varDelta", kind = "greek", glyph = "Δ", doc = "amsmath, italic capital delta" },
  { cmd = "varTheta", kind = "greek", glyph = "Θ", doc = "amsmath, italic capital theta" },
  { cmd = "varLambda", kind = "greek", glyph = "Λ", doc = "amsmath, italic capital lambda" },
  { cmd = "varXi", kind = "greek", glyph = "Ξ", doc = "amsmath, italic capital xi" },
  { cmd = "varPi", kind = "greek", glyph = "Π", doc = "amsmath, italic capital pi" },
  { cmd = "varSigma", kind = "greek", glyph = "Σ", doc = "amsmath, italic capital sigma" },
  { cmd = "varUpsilon", kind = "greek", glyph = "Υ", doc = "amsmath, italic capital upsilon" },
  { cmd = "varPhi", kind = "greek", glyph = "Φ", doc = "amsmath, italic capital phi" },
  { cmd = "varPsi", kind = "greek", glyph = "Ψ", doc = "amsmath, italic capital psi" },
  { cmd = "varOmega", kind = "greek", glyph = "Ω", doc = "amsmath, italic capital omega" },

  -- kind: letterlike -------------------------------------------------------
  { cmd = "ell", kind = "letterlike", glyph = "ℓ", doc = "Script small l" },
  { cmd = "hbar", kind = "letterlike", glyph = "ℏ", doc = "Planck constant over two pi" },
  { cmd = "hslash", kind = "letterlike", glyph = "ℏ", doc = "amssymb: h with stroke" },
  { cmd = "imath", kind = "letterlike", glyph = "ı", doc = "Dotless i (for accents)" },
  { cmd = "jmath", kind = "letterlike", glyph = "ȷ", doc = "Dotless j (for accents)" },
  { cmd = "Re", kind = "letterlike", glyph = "ℜ", aliases = { "real part" }, doc = "Real part" },
  { cmd = "Im", kind = "letterlike", glyph = "ℑ", aliases = { "imaginary part" }, doc = "Imaginary part" },
  { cmd = "wp", kind = "letterlike", glyph = "℘", aliases = { "weierstrass" }, doc = "Weierstrass p" },
  { cmd = "aleph", kind = "letterlike", glyph = "ℵ", doc = "Hebrew aleph (cardinal)" },
  { cmd = "beth", kind = "letterlike", glyph = "ℶ", doc = "amssymb: Hebrew beth" },
  { cmd = "gimel", kind = "letterlike", glyph = "ℷ", doc = "amssymb: Hebrew gimel" },
  { cmd = "daleth", kind = "letterlike", glyph = "ℸ", doc = "amssymb: Hebrew daleth" },
  { cmd = "partial", kind = "letterlike", glyph = "∂", aliases = { "derivative" }, doc = "Partial differential" },
  { cmd = "nabla", kind = "letterlike", glyph = "∇", aliases = { "grad", "del" }, doc = "Nabla / gradient" },
  { cmd = "infty", kind = "letterlike", glyph = "∞", aliases = { "infinity" }, doc = "Infinity" },
  { cmd = "emptyset", kind = "letterlike", glyph = "∅", aliases = { "empty set" }, doc = "Empty set" },
  { cmd = "varnothing", kind = "letterlike", glyph = "∅", aliases = { "empty set" }, doc = "amssymb: empty set" },
  { cmd = "complement", kind = "letterlike", glyph = "∁", doc = "amssymb: set complement" },
  { cmd = "mho", kind = "letterlike", glyph = "℧", doc = "amssymb: inverted ohm sign" },
  { cmd = "eth", kind = "letterlike", glyph = "ð", doc = "amssymb: latin small letter eth" },
  { cmd = "Finv", kind = "letterlike", glyph = "Ⅎ", doc = "amssymb: turned capital F" },
  { cmd = "Game", kind = "letterlike", glyph = "⅁", doc = "amssymb: turned sans-serif capital G" },
  { cmd = "Bbbk", kind = "letterlike", glyph = "𝕜", doc = "amssymb: blackboard bold k" },

  -- kind: operator (binary operators) --------------------------------------
  { cmd = "pm", kind = "operator", glyph = "±", aliases = { "plus minus" }, doc = "Plus-or-minus" },
  { cmd = "mp", kind = "operator", glyph = "∓", aliases = { "minus plus" }, doc = "Minus-or-plus" },
  { cmd = "times", kind = "operator", glyph = "×", aliases = { "multiply", "cross" }, doc = "Multiplication sign" },
  { cmd = "div", kind = "operator", glyph = "÷", aliases = { "divide" }, doc = "Division sign" },
  { cmd = "cdot", kind = "operator", glyph = "⋅", aliases = { "dot product" }, doc = "Centred dot product" },
  { cmd = "setminus", kind = "operator", glyph = "∖", aliases = { "difference" }, doc = "Set difference" },
  { cmd = "cup", kind = "operator", glyph = "∪", aliases = { "union" }, doc = "Set union" },
  { cmd = "cap", kind = "operator", glyph = "∩", aliases = { "intersection" }, doc = "Set intersection" },
  { cmd = "uplus", kind = "operator", glyph = "⊎", doc = "Multiset union" },
  { cmd = "sqcup", kind = "operator", glyph = "⊔", doc = "Square cup (disjoint union)" },
  { cmd = "sqcap", kind = "operator", glyph = "⊓", doc = "Square cap" },
  { cmd = "vee", kind = "operator", glyph = "∨", aliases = { "or", "join" }, doc = "Logical or / join" },
  { cmd = "lor", kind = "operator", glyph = "∨", aliases = { "or" }, doc = "Logical or" },
  { cmd = "wedge", kind = "operator", glyph = "∧", aliases = { "and", "meet" }, doc = "Logical and / meet" },
  { cmd = "land", kind = "operator", glyph = "∧", aliases = { "and" }, doc = "Logical and" },
  { cmd = "oplus", kind = "operator", glyph = "⊕", aliases = { "direct sum", "xor" }, doc = "Circled plus" },
  { cmd = "ominus", kind = "operator", glyph = "⊖", doc = "Circled minus" },
  { cmd = "otimes", kind = "operator", glyph = "⊗", aliases = { "tensor" }, doc = "Circled times (tensor)" },
  { cmd = "oslash", kind = "operator", glyph = "⊘", doc = "Circled slash" },
  { cmd = "odot", kind = "operator", glyph = "⊙", doc = "Circled dot" },
  { cmd = "bigcirc", kind = "operator", glyph = "◯", doc = "Large circle" },
  { cmd = "amalg", kind = "operator", glyph = "⨿", doc = "Amalgamation / coproduct" },
  { cmd = "triangleleft", kind = "operator", glyph = "◁", doc = "Left-pointing triangle" },
  { cmd = "triangleright", kind = "operator", glyph = "▷", doc = "Right-pointing triangle" },
  { cmd = "bigtriangleup", kind = "operator", glyph = "△", doc = "Large up-pointing triangle" },
  { cmd = "bigtriangledown", kind = "operator", glyph = "▽", doc = "Large down-pointing triangle" },
  { cmd = "diamond", kind = "operator", glyph = "⋄", doc = "Diamond operator" },
  { cmd = "wr", kind = "operator", glyph = "≀", doc = "Wreath product" },
  { cmd = "dotplus", kind = "operator", glyph = "∔", doc = "amssymb: dot plus" },
  { cmd = "smallsetminus", kind = "operator", glyph = "∖", doc = "amssymb: small set difference" },
  { cmd = "Cap", kind = "operator", glyph = "⋒", aliases = { "double intersection" }, doc = "amssymb: double cap" },
  { cmd = "Cup", kind = "operator", glyph = "⋓", aliases = { "double union" }, doc = "amssymb: double cup" },
  { cmd = "barwedge", kind = "operator", glyph = "⊼", aliases = { "nand" }, doc = "amssymb: bar wedge" },
  { cmd = "veebar", kind = "operator", glyph = "⊻", aliases = { "xor" }, doc = "amssymb: vee bar" },
  { cmd = "boxplus", kind = "operator", glyph = "⊞", doc = "amssymb: squared plus" },
  { cmd = "boxminus", kind = "operator", glyph = "⊟", doc = "amssymb: squared minus" },
  { cmd = "boxtimes", kind = "operator", glyph = "⊠", doc = "amssymb: squared times" },
  { cmd = "boxdot", kind = "operator", glyph = "⊡", doc = "amssymb: squared dot" },
  { cmd = "ltimes", kind = "operator", glyph = "⋉", doc = "amssymb: left semidirect product" },
  { cmd = "rtimes", kind = "operator", glyph = "⋊", doc = "amssymb: right semidirect product" },
  { cmd = "intercal", kind = "operator", glyph = "⊺", aliases = { "transpose" }, doc = "amssymb: intercalate" },
  { cmd = "centerdot", kind = "operator", glyph = "·", doc = "amssymb: centred dot (binary)" },
  { cmd = "circledast", kind = "operator", glyph = "⊛", doc = "amssymb: circled asterisk (convolution)" },
  { cmd = "circledcirc", kind = "operator", glyph = "⊚", doc = "amssymb: circled ring" },
  { cmd = "circleddash", kind = "operator", glyph = "⊝", doc = "amssymb: circled dash" },
  { cmd = "curlyvee", kind = "operator", glyph = "⋎", doc = "amssymb: curly logical or" },
  { cmd = "curlywedge", kind = "operator", glyph = "⋏", doc = "amssymb: curly logical and" },

  -- kind: bigop (no bodies -- LuaSnip autosnippets own the limits) ---------
  { cmd = "sum", kind = "bigop", glyph = "∑", aliases = { "summation", "sigma" }, doc = "N-ary summation" },
  { cmd = "prod", kind = "bigop", glyph = "∏", aliases = { "product" }, doc = "N-ary product" },
  { cmd = "coprod", kind = "bigop", glyph = "∐", aliases = { "coproduct" }, doc = "N-ary coproduct" },
  { cmd = "int", kind = "bigop", glyph = "∫", aliases = { "integral" }, doc = "Integral" },
  { cmd = "iint", kind = "bigop", glyph = "∬", aliases = { "double integral" }, doc = "amsmath: double integral" },
  { cmd = "iiint", kind = "bigop", glyph = "∭", aliases = { "triple integral" }, doc = "amsmath: triple integral" },
  { cmd = "iiiint", kind = "bigop", glyph = "⨌", doc = "amsmath: quadruple integral" },
  { cmd = "idotsint", kind = "bigop", doc = "amsmath: integral, dots, integral" },
  { cmd = "oint", kind = "bigop", glyph = "∮", aliases = { "contour integral" }, doc = "Contour integral" },
  { cmd = "bigcup", kind = "bigop", glyph = "⋃", aliases = { "union" }, doc = "N-ary union" },
  { cmd = "bigcap", kind = "bigop", glyph = "⋂", aliases = { "intersection" }, doc = "N-ary intersection" },
  { cmd = "bigvee", kind = "bigop", glyph = "⋁", aliases = { "or" }, doc = "N-ary logical or" },
  { cmd = "bigwedge", kind = "bigop", glyph = "⋀", aliases = { "and" }, doc = "N-ary logical and" },
  { cmd = "bigoplus", kind = "bigop", glyph = "⨁", aliases = { "direct sum" }, doc = "N-ary circled plus" },
  { cmd = "bigotimes", kind = "bigop", glyph = "⨂", aliases = { "tensor" }, doc = "N-ary circled times" },
  { cmd = "bigodot", kind = "bigop", glyph = "⨀", doc = "N-ary circled dot" },
  { cmd = "biguplus", kind = "bigop", glyph = "⨄", doc = "N-ary multiset union" },
  { cmd = "bigsqcup", kind = "bigop", glyph = "⨆", doc = "N-ary square union" },

  -- kind: relation ---------------------------------------------------------
  { cmd = "leq", kind = "relation", glyph = "≤", aliases = { "less than or equal" }, doc = "Less than or equal to" },
  { cmd = "le", kind = "relation", glyph = "≤", aliases = { "less than or equal" }, doc = "Less than or equal to" },
  { cmd = "geq", kind = "relation", glyph = "≥", aliases = { "greater than or equal" }, doc = "Greater than or equal" },
  { cmd = "ge", kind = "relation", glyph = "≥", aliases = { "greater than or equal" }, doc = "Greater than or equal" },
  { cmd = "neq", kind = "relation", glyph = "≠", aliases = { "not equal" }, doc = "Not equal to" },
  { cmd = "ne", kind = "relation", glyph = "≠", aliases = { "not equal" }, doc = "Not equal to" },
  { cmd = "equiv", kind = "relation", glyph = "≡", aliases = { "equivalent" }, doc = "Identical to / congruent mod" },
  { cmd = "sim", kind = "relation", glyph = "∼", aliases = { "similar", "tilde" }, doc = "Similar to" },
  { cmd = "simeq", kind = "relation", glyph = "≃", doc = "Asymptotically equal to" },
  { cmd = "approx", kind = "relation", glyph = "≈", aliases = { "approximately" }, doc = "Approximately equal to" },
  { cmd = "cong", kind = "relation", glyph = "≅", aliases = { "congruent", "isomorphic" }, doc = "Congruent to" },
  { cmd = "propto", kind = "relation", glyph = "∝", aliases = { "proportional" }, doc = "Proportional to" },
  { cmd = "asymp", kind = "relation", glyph = "≍", doc = "Asymptotic to" },
  { cmd = "doteq", kind = "relation", glyph = "≐", doc = "Approaches the limit" },
  { cmd = "subset", kind = "relation", glyph = "⊂", doc = "Subset of" },
  { cmd = "supset", kind = "relation", glyph = "⊃", doc = "Superset of" },
  { cmd = "subseteq", kind = "relation", glyph = "⊆", doc = "Subset of or equal to" },
  { cmd = "supseteq", kind = "relation", glyph = "⊇", doc = "Superset of or equal to" },
  { cmd = "sqsubseteq", kind = "relation", glyph = "⊑", doc = "Square subset of or equal to" },
  { cmd = "sqsupseteq", kind = "relation", glyph = "⊒", doc = "Square superset of or equal to" },
  { cmd = "in", kind = "relation", glyph = "∈", aliases = { "element", "member" }, doc = "Element of" },
  { cmd = "notin", kind = "relation", glyph = "∉", aliases = { "not element" }, doc = "Not an element of" },
  { cmd = "ni", kind = "relation", glyph = "∋", doc = "Contains as member" },
  { cmd = "owns", kind = "relation", glyph = "∋", doc = "Contains as member" },
  { cmd = "ll", kind = "relation", glyph = "≪", aliases = { "much less" }, doc = "Much less than" },
  { cmd = "gg", kind = "relation", glyph = "≫", aliases = { "much greater" }, doc = "Much greater than" },
  { cmd = "prec", kind = "relation", glyph = "≺", doc = "Precedes" },
  { cmd = "succ", kind = "relation", glyph = "≻", doc = "Succeeds" },
  { cmd = "preceq", kind = "relation", glyph = "⪯", doc = "Precedes or equals" },
  { cmd = "succeq", kind = "relation", glyph = "⪰", doc = "Succeeds or equals" },
  { cmd = "mid", kind = "relation", glyph = "∣", aliases = { "divides", "such that" }, doc = "Divides / such that" },
  { cmd = "parallel", kind = "relation", glyph = "∥", doc = "Parallel to" },
  { cmd = "perp", kind = "relation", glyph = "⊥", aliases = { "orthogonal" }, doc = "Perpendicular to" },
  { cmd = "bowtie", kind = "relation", glyph = "⋈", aliases = { "join" }, doc = "Bowtie (natural join)" },
  { cmd = "frown", kind = "relation", glyph = "⌢", doc = "Frown" },
  { cmd = "smile", kind = "relation", glyph = "⌣", doc = "Smile" },
  { cmd = "leqslant", kind = "relation", glyph = "⩽", doc = "amssymb: less than or slanted equal" },
  { cmd = "geqslant", kind = "relation", glyph = "⩾", doc = "amssymb: greater than or slanted equal" },
  { cmd = "leqq", kind = "relation", glyph = "≦", doc = "amssymb: less than over equal to" },
  { cmd = "geqq", kind = "relation", glyph = "≧", doc = "amssymb: greater than over equal to" },
  { cmd = "lesssim", kind = "relation", glyph = "≲", doc = "amssymb: less than or equivalent to" },
  { cmd = "gtrsim", kind = "relation", glyph = "≳", doc = "amssymb: greater than or equivalent to" },
  { cmd = "lessgtr", kind = "relation", glyph = "≶", doc = "amssymb: less than or greater than" },
  { cmd = "gtrless", kind = "relation", glyph = "≷", doc = "amssymb: greater than or less than" },
  { cmd = "nleq", kind = "relation", glyph = "≰", doc = "amssymb: not less than or equal" },
  { cmd = "ngeq", kind = "relation", glyph = "≱", doc = "amssymb: not greater than or equal" },
  { cmd = "nless", kind = "relation", glyph = "≮", doc = "amssymb: not less than" },
  { cmd = "ngtr", kind = "relation", glyph = "≯", doc = "amssymb: not greater than" },
  { cmd = "nsim", kind = "relation", glyph = "≁", doc = "amssymb: not similar to" },
  { cmd = "ncong", kind = "relation", glyph = "≇", doc = "amssymb: not congruent to" },
  { cmd = "subsetneq", kind = "relation", glyph = "⊊", doc = "amssymb: proper subset" },
  { cmd = "supsetneq", kind = "relation", glyph = "⊋", doc = "amssymb: proper superset" },
  { cmd = "nsubseteq", kind = "relation", glyph = "⊈", doc = "amssymb: not a subset of or equal" },
  { cmd = "nsupseteq", kind = "relation", glyph = "⊉", doc = "amssymb: not a superset of or equal" },
  { cmd = "subseteqq", kind = "relation", glyph = "⫅", doc = "amssymb: subset of above equals" },
  { cmd = "supseteqq", kind = "relation", glyph = "⫆", doc = "amssymb: superset of above equals" },
  { cmd = "nmid", kind = "relation", glyph = "∤", doc = "amssymb: does not divide" },
  { cmd = "nparallel", kind = "relation", glyph = "∦", doc = "amssymb: not parallel to" },
  { cmd = "shortmid", kind = "relation", glyph = "∣", doc = "amssymb: short divides" },
  { cmd = "shortparallel", kind = "relation", glyph = "∥", doc = "amssymb: short parallel" },
  { cmd = "smallfrown", kind = "relation", glyph = "⌢", doc = "amssymb: small frown" },
  { cmd = "smallsmile", kind = "relation", glyph = "⌣", doc = "amssymb: small smile" },
  { cmd = "approxeq", kind = "relation", glyph = "≊", doc = "amssymb: almost equal or equal to" },
  { cmd = "backsim", kind = "relation", glyph = "∽", doc = "amssymb: reversed tilde" },
  { cmd = "backsimeq", kind = "relation", glyph = "⋍", doc = "amssymb: reversed tilde equals" },
  { cmd = "thicksim", kind = "relation", glyph = "∼", doc = "amssymb: thick similar to" },
  { cmd = "thickapprox", kind = "relation", glyph = "≈", doc = "amssymb: thick approximately equal" },
  { cmd = "precsim", kind = "relation", glyph = "≾", doc = "amssymb: precedes or equivalent to" },
  { cmd = "succsim", kind = "relation", glyph = "≿", doc = "amssymb: succeeds or equivalent to" },
  { cmd = "preccurlyeq", kind = "relation", glyph = "≼", doc = "amssymb: precedes or equal to" },
  { cmd = "succcurlyeq", kind = "relation", glyph = "≽", doc = "amssymb: succeeds or equal to" },
  { cmd = "curlyeqprec", kind = "relation", glyph = "⋞", doc = "amssymb: equal to or precedes" },
  { cmd = "curlyeqsucc", kind = "relation", glyph = "⋟", doc = "amssymb: equal to or succeeds" },
  { cmd = "triangleq", kind = "relation", glyph = "≜", aliases = { "defined as" }, doc = "amssymb: delta equal to" },
  { cmd = "eqcirc", kind = "relation", glyph = "≖", doc = "amssymb: ring in equal to" },
  { cmd = "circeq", kind = "relation", glyph = "≗", doc = "amssymb: ring equal to" },
  { cmd = "bumpeq", kind = "relation", glyph = "≏", doc = "amssymb: difference between" },
  { cmd = "Bumpeq", kind = "relation", glyph = "≎", doc = "amssymb: geometrically equivalent to" },
  { cmd = "doteqdot", kind = "relation", glyph = "≑", doc = "amssymb: geometrically equal to" },
  { cmd = "risingdotseq", kind = "relation", glyph = "≓", doc = "amssymb: image of or approximately" },
  { cmd = "fallingdotseq", kind = "relation", glyph = "≒", doc = "amssymb: approximately equal or image" },
  { cmd = "vartriangleleft", kind = "relation", glyph = "⊲", doc = "amssymb: normal subgroup of" },
  { cmd = "vartriangleright", kind = "relation", glyph = "⊳", doc = "amssymb: contains as normal subgroup" },
  { cmd = "trianglelefteq", kind = "relation", glyph = "⊴", doc = "amssymb: normal subgroup of or equal" },
  { cmd = "trianglerighteq", kind = "relation", glyph = "⊵", doc = "amssymb: contains normal subgroup or equal" },
  { cmd = "between", kind = "relation", glyph = "≬", doc = "amssymb: between" },
  { cmd = "pitchfork", kind = "relation", glyph = "⋔", doc = "amssymb: transversal intersection" },
  { cmd = "backepsilon", kind = "relation", glyph = "϶", doc = "amssymb: small contains as member" },
  { cmd = "coloneqq", kind = "relation", glyph = "≔", aliases = { "assign" }, doc = "mathtools: colon equals" },
  { cmd = "eqqcolon", kind = "relation", glyph = "≕", doc = "mathtools: equals colon" },
  { cmd = "vcentcolon", kind = "relation", glyph = "∶", doc = "mathtools: vertically centred colon" },

  -- kind: arrow ------------------------------------------------------------
  { cmd = "to", kind = "arrow", glyph = "→", aliases = { "arrow", "rightarrow" }, doc = "Rightwards arrow" },
  { cmd = "rightarrow", kind = "arrow", glyph = "→", aliases = { "arrow" }, doc = "Rightwards arrow" },
  { cmd = "gets", kind = "arrow", glyph = "←", aliases = { "arrow", "leftarrow" }, doc = "Leftwards arrow" },
  { cmd = "leftarrow", kind = "arrow", glyph = "←", aliases = { "arrow" }, doc = "Leftwards arrow" },
  { cmd = "leftrightarrow", kind = "arrow", glyph = "↔", doc = "Left right arrow" },
  { cmd = "Rightarrow", kind = "arrow", glyph = "⇒", aliases = { "implies" }, doc = "Rightwards double arrow" },
  { cmd = "Leftarrow", kind = "arrow", glyph = "⇐", doc = "Leftwards double arrow" },
  { cmd = "Leftrightarrow", kind = "arrow", glyph = "⇔", aliases = { "iff" }, doc = "Left right double arrow" },
  { cmd = "longrightarrow", kind = "arrow", glyph = "⟶", doc = "Long rightwards arrow" },
  { cmd = "longleftarrow", kind = "arrow", glyph = "⟵", doc = "Long leftwards arrow" },
  { cmd = "longleftrightarrow", kind = "arrow", glyph = "⟷", doc = "Long left right arrow" },
  { cmd = "Longrightarrow", kind = "arrow", glyph = "⟹", doc = "Long rightwards double arrow" },
  { cmd = "Longleftarrow", kind = "arrow", glyph = "⟸", doc = "Long leftwards double arrow" },
  { cmd = "Longleftrightarrow", kind = "arrow", glyph = "⟺", doc = "Long left right double arrow" },
  { cmd = "implies", kind = "arrow", glyph = "⟹", aliases = { "therefore" }, doc = "amsmath: implies (spaced)" },
  { cmd = "impliedby", kind = "arrow", glyph = "⟸", doc = "amsmath: implied by (spaced)" },
  { cmd = "iff", kind = "arrow", glyph = "⟺", aliases = { "if and only if" }, doc = "amsmath: if and only if" },
  { cmd = "mapsto", kind = "arrow", glyph = "↦", aliases = { "maps to" }, doc = "Maps to" },
  { cmd = "longmapsto", kind = "arrow", glyph = "⟼", doc = "Long maps to" },
  { cmd = "uparrow", kind = "arrow", glyph = "↑", doc = "Upwards arrow" },
  { cmd = "downarrow", kind = "arrow", glyph = "↓", doc = "Downwards arrow" },
  { cmd = "updownarrow", kind = "arrow", glyph = "↕", doc = "Up down arrow" },
  { cmd = "Uparrow", kind = "arrow", glyph = "⇑", doc = "Upwards double arrow" },
  { cmd = "Downarrow", kind = "arrow", glyph = "⇓", doc = "Downwards double arrow" },
  { cmd = "Updownarrow", kind = "arrow", glyph = "⇕", doc = "Up down double arrow" },
  { cmd = "nearrow", kind = "arrow", glyph = "↗", doc = "North east arrow" },
  { cmd = "searrow", kind = "arrow", glyph = "↘", doc = "South east arrow" },
  { cmd = "swarrow", kind = "arrow", glyph = "↙", doc = "South west arrow" },
  { cmd = "nwarrow", kind = "arrow", glyph = "↖", doc = "North west arrow" },
  { cmd = "hookrightarrow", kind = "arrow", glyph = "↪", aliases = { "injection" }, doc = "Arrow with hook" },
  { cmd = "hookleftarrow", kind = "arrow", glyph = "↩", doc = "Leftwards arrow with hook" },
  { cmd = "rightharpoonup", kind = "arrow", glyph = "⇀", doc = "Rightwards harpoon with barb up" },
  { cmd = "rightharpoondown", kind = "arrow", glyph = "⇁", doc = "Rightwards harpoon with barb down" },
  { cmd = "leftharpoonup", kind = "arrow", glyph = "↼", doc = "Leftwards harpoon with barb up" },
  { cmd = "leftharpoondown", kind = "arrow", glyph = "↽", doc = "Leftwards harpoon with barb down" },
  { cmd = "rightleftharpoons", kind = "arrow", glyph = "⇌", aliases = { "equilibrium" }, doc = "Paired harpoons" },
  { cmd = "leadsto", kind = "arrow", glyph = "⇝", doc = "amssymb: rightwards squiggle arrow" },
  { cmd = "rightsquigarrow", kind = "arrow", glyph = "⇝", doc = "amssymb: rightwards squiggle arrow" },
  { cmd = "twoheadrightarrow", kind = "arrow", glyph = "↠", aliases = { "surjection" }, doc = "amssymb: onto arrow" },
  { cmd = "twoheadleftarrow", kind = "arrow", glyph = "↞", doc = "amssymb: two-headed leftwards arrow" },
  { cmd = "rightrightarrows", kind = "arrow", glyph = "⇉", doc = "amssymb: rightwards paired arrows" },
  { cmd = "leftleftarrows", kind = "arrow", glyph = "⇇", doc = "amssymb: leftwards paired arrows" },
  { cmd = "rightleftarrows", kind = "arrow", glyph = "⇄", doc = "amssymb: rightwards over leftwards arrow" },
  { cmd = "leftrightarrows", kind = "arrow", glyph = "⇆", doc = "amssymb: leftwards over rightwards arrow" },
  { cmd = "circlearrowleft", kind = "arrow", glyph = "↺", doc = "amssymb: anticlockwise open circle arrow" },
  { cmd = "circlearrowright", kind = "arrow", glyph = "↻", doc = "amssymb: clockwise open circle arrow" },
  { cmd = "curvearrowleft", kind = "arrow", glyph = "↶", doc = "amssymb: anticlockwise top semicircle arrow" },
  { cmd = "curvearrowright", kind = "arrow", glyph = "↷", doc = "amssymb: clockwise top semicircle arrow" },
  { cmd = "multimap", kind = "arrow", glyph = "⊸", doc = "amssymb: multimap (linear logic)" },
  { cmd = "nrightarrow", kind = "arrow", glyph = "↛", doc = "amssymb: rightwards arrow with stroke" },
  { cmd = "nleftarrow", kind = "arrow", glyph = "↚", doc = "amssymb: leftwards arrow with stroke" },
  { cmd = "nRightarrow", kind = "arrow", glyph = "⇏", doc = "amssymb: rightwards double arrow with stroke" },
  { cmd = "nLeftarrow", kind = "arrow", glyph = "⇍", doc = "amssymb: leftwards double arrow with stroke" },
  { cmd = "nleftrightarrow", kind = "arrow", glyph = "↮", doc = "amssymb: left right arrow with stroke" },
  { cmd = "nLeftrightarrow", kind = "arrow", glyph = "⇎", doc = "amssymb: left right double arrow with stroke" },
  { cmd = "dashrightarrow", kind = "arrow", glyph = "⇢", doc = "amssymb: rightwards dashed arrow" },
  { cmd = "dashleftarrow", kind = "arrow", glyph = "⇠", doc = "amssymb: leftwards dashed arrow" },
  {
    cmd = "xrightarrow", kind = "arrow", label = "\\xrightarrow{}", body = "\\xrightarrow{$1}",
    aliases = { "labelled arrow", "over arrow" }, doc = "amsmath: rightwards arrow with text above",
  },
  {
    cmd = "xleftarrow", kind = "arrow", label = "\\xleftarrow{}", body = "\\xleftarrow{$1}",
    aliases = { "labelled arrow" }, doc = "amsmath: leftwards arrow with text above",
  },
  {
    cmd = "xleftrightarrow", kind = "arrow", label = "\\xleftrightarrow{}", body = "\\xleftrightarrow{$1}",
    aliases = { "labelled arrow" }, doc = "mathtools: left right arrow with text above",
  },

  -- kind: delimiter --------------------------------------------------------
  { cmd = "langle", kind = "delimiter", glyph = "⟨", aliases = { "bra", "angle bracket" }, doc = "Left angle bracket" },
  { cmd = "rangle", kind = "delimiter", glyph = "⟩", aliases = { "ket", "angle" }, doc = "Right angle bracket" },
  { cmd = "lfloor", kind = "delimiter", glyph = "⌊", aliases = { "floor" }, doc = "Left floor" },
  { cmd = "rfloor", kind = "delimiter", glyph = "⌋", aliases = { "floor" }, doc = "Right floor" },
  { cmd = "lceil", kind = "delimiter", glyph = "⌈", aliases = { "ceiling" }, doc = "Left ceiling" },
  { cmd = "rceil", kind = "delimiter", glyph = "⌉", aliases = { "ceiling" }, doc = "Right ceiling" },
  { cmd = "lvert", kind = "delimiter", glyph = "|", aliases = { "abs" }, doc = "amsmath: left vertical bar" },
  { cmd = "rvert", kind = "delimiter", glyph = "|", aliases = { "abs" }, doc = "amsmath: right vertical bar" },
  { cmd = "lVert", kind = "delimiter", glyph = "‖", aliases = { "norm" }, doc = "amsmath: left double vertical bar" },
  { cmd = "rVert", kind = "delimiter", glyph = "‖", aliases = { "norm" }, doc = "amsmath: right double vertical bar" },
  { cmd = "vert", kind = "delimiter", glyph = "|", aliases = { "abs", "pipe" }, doc = "Vertical bar" },
  { cmd = "Vert", kind = "delimiter", glyph = "‖", aliases = { "norm" }, doc = "Double vertical bar" },
  { cmd = "{", kind = "delimiter", glyph = "{", aliases = { "brace", "curly" }, doc = "Literal left brace" },
  { cmd = "}", kind = "delimiter", glyph = "}", aliases = { "brace", "curly" }, doc = "Literal right brace" },
  { cmd = "|", kind = "delimiter", glyph = "‖", aliases = { "norm", "double bar" }, doc = "Double vertical bar" },
  { cmd = "lparen", kind = "delimiter", glyph = "(", aliases = { "paren" }, doc = "mathtools: left parenthesis" },
  { cmd = "rparen", kind = "delimiter", glyph = ")", aliases = { "paren" }, doc = "mathtools: right parenthesis" },
  { cmd = "ulcorner", kind = "delimiter", glyph = "⌜", aliases = { "corner" }, doc = "amssymb: upper left corner" },
  { cmd = "urcorner", kind = "delimiter", glyph = "⌝", aliases = { "corner" }, doc = "amssymb: upper right corner" },
  { cmd = "llcorner", kind = "delimiter", glyph = "⌞", aliases = { "corner" }, doc = "amssymb: lower left corner" },
  { cmd = "lrcorner", kind = "delimiter", glyph = "⌟", aliases = { "corner" }, doc = "amssymb: lower right corner" },
  {
    cmd = "left", kind = "delimiter", label = "\\left( \\right)", body = "\\left($1\\right)$0",
    aliases = { "paren", "parentheses" }, doc = "Auto-sized parentheses",
  },
  {
    cmd = "leftbracket", kind = "delimiter", label = "\\left[ \\right]", body = "\\left[$1\\right]$0",
    aliases = { "left", "bracket", "square bracket" }, doc = "Auto-sized square brackets",
  },
  {
    cmd = "leftbrace", kind = "delimiter", label = "\\left\\{ \\right\\}", body = "\\left\\{$1\\right\\\\}$0",
    aliases = { "left", "brace", "curly", "set" }, doc = "Auto-sized curly braces",
  },
  {
    cmd = "leftangle", kind = "delimiter", label = "\\left\\langle \\right\\rangle",
    body = "\\left\\langle $1\\right\\rangle$0",
    aliases = { "left", "angle", "bra ket", "inner product" }, doc = "Auto-sized angle brackets",
  },
  {
    cmd = "leftabs", kind = "delimiter", label = "\\left| \\right|", body = "\\left|$1\\right|$0",
    aliases = { "left", "abs", "absolute value", "modulus" }, doc = "Auto-sized absolute value bars",
  },
  {
    cmd = "leftnorm", kind = "delimiter", label = "\\left\\| \\right\\|", body = "\\left\\|$1\\right\\|$0",
    aliases = { "left", "norm", "magnitude" }, doc = "Auto-sized norm bars",
  },
  {
    cmd = "leftfloor", kind = "delimiter", label = "\\left\\lfloor \\right\\rfloor",
    body = "\\left\\lfloor $1\\right\\rfloor$0",
    aliases = { "left", "floor" }, doc = "Auto-sized floor brackets",
  },
  {
    cmd = "leftceil", kind = "delimiter", label = "\\left\\lceil \\right\\rceil",
    body = "\\left\\lceil $1\\right\\rceil$0",
    aliases = { "left", "ceil", "ceiling" }, doc = "Auto-sized ceiling brackets",
  },

  -- kind: accent -----------------------------------------------------------
  { cmd = "hat", kind = "accent", label = "\\hat{}", body = "\\hat{$1}", aliases = { "circumflex" }, doc = "Hat" },
  { cmd = "widehat", kind = "accent", label = "\\widehat{}", body = "\\widehat{$1}", doc = "Wide hat accent" },
  { cmd = "tilde", kind = "accent", label = "\\tilde{}", body = "\\tilde{$1}", doc = "Tilde accent" },
  { cmd = "widetilde", kind = "accent", label = "\\widetilde{}", body = "\\widetilde{$1}", doc = "Wide tilde accent" },
  { cmd = "bar", kind = "accent", label = "\\bar{}", body = "\\bar{$1}", aliases = { "mean" }, doc = "Bar (macron)" },
  {
    cmd = "overline", kind = "accent", label = "\\overline{}", body = "\\overline{$1}",
    aliases = { "conjugate", "closure" }, doc = "Line over the argument",
  },
  { cmd = "underline", kind = "accent", label = "\\underline{}", body = "\\underline{$1}", doc = "Line underneath" },
  { cmd = "vec", kind = "accent", label = "\\vec{}", body = "\\vec{$1}", aliases = { "vector" }, doc = "Vector arrow" },
  {
    cmd = "overrightarrow", kind = "accent", label = "\\overrightarrow{}", body = "\\overrightarrow{$1}",
    aliases = { "vector" }, doc = "Wide rightwards arrow over the argument",
  },
  {
    cmd = "overleftarrow", kind = "accent", label = "\\overleftarrow{}", body = "\\overleftarrow{$1}",
    doc = "Wide leftwards arrow over the argument",
  },
  { cmd = "dot", kind = "accent", label = "\\dot{}", body = "\\dot{$1}", aliases = { "derivative" }, doc = "Dot" },
  { cmd = "ddot", kind = "accent", label = "\\ddot{}", body = "\\ddot{$1}", doc = "Double dot accent" },
  { cmd = "dddot", kind = "accent", label = "\\dddot{}", body = "\\dddot{$1}", doc = "amsmath: triple dot accent" },
  { cmd = "breve", kind = "accent", label = "\\breve{}", body = "\\breve{$1}", doc = "Breve accent" },
  { cmd = "check", kind = "accent", label = "\\check{}", body = "\\check{$1}", aliases = { "caron" }, doc = "Caron" },
  { cmd = "acute", kind = "accent", label = "\\acute{}", body = "\\acute{$1}", doc = "Acute accent" },
  { cmd = "grave", kind = "accent", label = "\\grave{}", body = "\\grave{$1}", doc = "Grave accent" },
  { cmd = "mathring", kind = "accent", label = "\\mathring{}", body = "\\mathring{$1}", doc = "Ring accent" },
  {
    cmd = "overbrace", kind = "accent", label = "\\overbrace{}^{}", body = "\\overbrace{$1}^{$2}",
    aliases = { "brace" }, doc = "Horizontal brace above with a label",
  },
  {
    cmd = "underbrace", kind = "accent", label = "\\underbrace{}_{}", body = "\\underbrace{$1}_{$2}",
    aliases = { "brace" }, doc = "Horizontal brace below with a label",
  },
  {
    cmd = "overbracket", kind = "accent", label = "\\overbracket{}", body = "\\overbracket{$1}",
    doc = "mathtools: square bracket above",
  },
  {
    cmd = "underbracket", kind = "accent", label = "\\underbracket{}", body = "\\underbracket{$1}",
    doc = "mathtools: square bracket below",
  },
  {
    cmd = "overset", kind = "accent", label = "\\overset{}{}", body = "\\overset{$1}{$2}",
    doc = "amsmath: place the first argument above the second",
  },
  {
    cmd = "underset", kind = "accent", label = "\\underset{}{}", body = "\\underset{$1}{$2}",
    doc = "amsmath: place the first argument below the second",
  },
  {
    cmd = "stackrel", kind = "accent", label = "\\stackrel{}{}", body = "\\stackrel{$1}{$2}",
    doc = "Stack the first argument above a relation",
  },

  -- kind: function (log-like operators; plain, autosnippets own the limits) -
  { cmd = "sin", kind = "function", doc = "Sine" },
  { cmd = "cos", kind = "function", doc = "Cosine" },
  { cmd = "tan", kind = "function", doc = "Tangent" },
  { cmd = "cot", kind = "function", doc = "Cotangent" },
  { cmd = "sec", kind = "function", doc = "Secant" },
  { cmd = "csc", kind = "function", doc = "Cosecant" },
  { cmd = "arcsin", kind = "function", doc = "Inverse sine" },
  { cmd = "arccos", kind = "function", doc = "Inverse cosine" },
  { cmd = "arctan", kind = "function", doc = "Inverse tangent" },
  { cmd = "sinh", kind = "function", doc = "Hyperbolic sine" },
  { cmd = "cosh", kind = "function", doc = "Hyperbolic cosine" },
  { cmd = "tanh", kind = "function", doc = "Hyperbolic tangent" },
  { cmd = "coth", kind = "function", doc = "Hyperbolic cotangent" },
  { cmd = "exp", kind = "function", aliases = { "exponential" }, doc = "Exponential function" },
  { cmd = "log", kind = "function", aliases = { "logarithm" }, doc = "Logarithm" },
  { cmd = "ln", kind = "function", aliases = { "natural log" }, doc = "Natural logarithm" },
  { cmd = "lg", kind = "function", doc = "Base-2 logarithm" },
  { cmd = "arg", kind = "function", doc = "Argument of a complex number" },
  { cmd = "deg", kind = "function", doc = "Degree" },
  { cmd = "det", kind = "function", aliases = { "determinant" }, doc = "Determinant" },
  { cmd = "dim", kind = "function", aliases = { "dimension" }, doc = "Dimension" },
  { cmd = "gcd", kind = "function", doc = "Greatest common divisor" },
  { cmd = "hom", kind = "function", doc = "Hom functor" },
  { cmd = "inf", kind = "function", aliases = { "infimum" }, doc = "Infimum" },
  { cmd = "ker", kind = "function", aliases = { "kernel" }, doc = "Kernel" },
  { cmd = "lim", kind = "function", aliases = { "limit" }, doc = "Limit" },
  { cmd = "liminf", kind = "function", doc = "Limit inferior" },
  { cmd = "limsup", kind = "function", doc = "Limit superior" },
  { cmd = "max", kind = "function", aliases = { "maximum" }, doc = "Maximum" },
  { cmd = "min", kind = "function", aliases = { "minimum" }, doc = "Minimum" },
  { cmd = "Pr", kind = "function", aliases = { "probability" }, doc = "Probability" },
  { cmd = "sup", kind = "function", aliases = { "supremum" }, doc = "Supremum" },
  { cmd = "varinjlim", kind = "function", aliases = { "colimit", "direct limit" }, doc = "amsmath: injective limit" },
  { cmd = "varprojlim", kind = "function", aliases = { "inverse limit" }, doc = "amsmath: projective limit" },
  { cmd = "varliminf", kind = "function", doc = "amsmath: limit inferior (underlined lim)" },
  { cmd = "varlimsup", kind = "function", doc = "amsmath: limit superior (overlined lim)" },
  {
    cmd = "operatorname", kind = "function", label = "\\operatorname{}", body = "\\operatorname{$1}",
    aliases = { "custom operator" }, doc = "amsmath: typeset a custom operator name upright",
  },

  -- kind: structure --------------------------------------------------------
  {
    cmd = "frac", kind = "structure", label = "\\frac{}{}", body = "\\frac{$1}{$2}",
    aliases = { "fraction", "over", "divide" }, doc = "Fraction: numerator over denominator",
  },
  {
    cmd = "dfrac", kind = "structure", label = "\\dfrac{}{}", body = "\\dfrac{$1}{$2}",
    aliases = { "fraction", "display" }, doc = "amsmath: display-style fraction",
  },
  {
    cmd = "tfrac", kind = "structure", label = "\\tfrac{}{}", body = "\\tfrac{$1}{$2}",
    aliases = { "fraction", "text" }, doc = "amsmath: text-style (small) fraction",
  },
  {
    cmd = "cfrac", kind = "structure", label = "\\cfrac{}{}", body = "\\cfrac{$1}{$2}",
    aliases = { "fraction", "continued" }, doc = "amsmath: continued fraction",
  },
  {
    cmd = "binom", kind = "structure", label = "\\binom{}{}", body = "\\binom{$1}{$2}",
    aliases = { "choose", "binomial", "combination" }, doc = "amsmath: binomial coefficient",
  },
  {
    cmd = "dbinom", kind = "structure", label = "\\dbinom{}{}", body = "\\dbinom{$1}{$2}",
    aliases = { "choose", "display" }, doc = "amsmath: display-style binomial coefficient",
  },
  {
    cmd = "tbinom", kind = "structure", label = "\\tbinom{}{}", body = "\\tbinom{$1}{$2}",
    aliases = { "choose", "text" }, doc = "amsmath: text-style binomial coefficient",
  },
  {
    cmd = "sqrt", kind = "structure", label = "\\sqrt{}", body = "\\sqrt{$1}",
    aliases = { "root", "radical", "square root" }, doc = "Square root",
  },
  {
    cmd = "sqrtn", kind = "structure", label = "\\sqrt[n]{}", body = "\\sqrt[$1]{$2}",
    aliases = { "sqrt[n]", "root", "nth root", "radical" }, doc = "N-th root",
  },
  {
    cmd = "boxed", kind = "structure", label = "\\boxed{}", body = "\\boxed{$1}",
    aliases = { "box", "frame", "highlight" }, doc = "amsmath: draw a box around the argument",
  },
  {
    cmd = "phantom", kind = "structure", label = "\\phantom{}", body = "\\phantom{$1}",
    aliases = { "spacer", "invisible" }, doc = "Invisible box with the argument's full size",
  },
  {
    cmd = "vphantom", kind = "structure", label = "\\vphantom{}", body = "\\vphantom{$1}",
    aliases = { "spacer" }, doc = "Invisible box with the argument's height only",
  },
  {
    cmd = "hphantom", kind = "structure", label = "\\hphantom{}", body = "\\hphantom{$1}",
    aliases = { "spacer" }, doc = "Invisible box with the argument's width only",
  },
  {
    cmd = "smash", kind = "structure", label = "\\smash{}", body = "\\smash{$1}",
    doc = "Typeset the argument with zero height and depth",
  },
  {
    cmd = "substack", kind = "structure", label = "\\substack{}", body = "\\substack{$1 \\\\\\\\ $2}",
    aliases = { "multiline subscript" }, doc = "amsmath: stacked multi-line sub/superscript",
  },
  {
    cmd = "prescript", kind = "structure", label = "\\prescript{}{}{}", body = "\\prescript{$1}{$2}{$3}",
    aliases = { "presubscript", "left index" }, doc = "mathtools: pre-sub/superscripts on a symbol",
  },
  {
    cmd = "mathclap", kind = "structure", label = "\\mathclap{}", body = "\\mathclap{$1}",
    doc = "mathtools: typeset with zero width, centred",
  },
  {
    cmd = "mathllap", kind = "structure", label = "\\mathllap{}", body = "\\mathllap{$1}",
    doc = "mathtools: typeset with zero width, overlapping left",
  },
  {
    cmd = "mathrlap", kind = "structure", label = "\\mathrlap{}", body = "\\mathrlap{$1}",
    doc = "mathtools: typeset with zero width, overlapping right",
  },
  { cmd = "mathstrut", kind = "structure", doc = "Invisible strut with the height of a parenthesis" },
  { cmd = "not", kind = "structure", aliases = { "negate", "slash" }, doc = "Slash through the next symbol" },
  { cmd = "limits", kind = "structure", doc = "Force limits above/below the preceding operator" },
  { cmd = "nolimits", kind = "structure", doc = "Force limits beside the preceding operator" },

  -- kind: font -------------------------------------------------------------
  {
    cmd = "mathrm", kind = "font", label = "\\mathrm{}", body = "\\mathrm{$1}",
    aliases = { "roman", "upright" }, doc = "Upright roman math letters",
  },
  {
    cmd = "mathbf", kind = "font", label = "\\mathbf{}", body = "\\mathbf{$1}",
    aliases = { "bold", "vector" }, doc = "Bold math letters",
  },
  {
    cmd = "mathit", kind = "font", label = "\\mathit{}", body = "\\mathit{$1}",
    aliases = { "italic" }, doc = "Italic math letters",
  },
  {
    cmd = "mathsf", kind = "font", label = "\\mathsf{}", body = "\\mathsf{$1}",
    aliases = { "sans serif" }, doc = "Sans-serif math letters",
  },
  {
    cmd = "mathtt", kind = "font", label = "\\mathtt{}", body = "\\mathtt{$1}",
    aliases = { "monospace", "typewriter" }, doc = "Typewriter math letters",
  },
  {
    cmd = "mathcal", kind = "font", label = "\\mathcal{}", body = "\\mathcal{$1}",
    aliases = { "calligraphic", "script" }, doc = "Calligraphic capitals",
  },
  {
    cmd = "mathfrak", kind = "font", label = "\\mathfrak{}", body = "\\mathfrak{$1}",
    aliases = { "fraktur", "gothic" }, doc = "amsfonts: fraktur letters",
  },
  {
    cmd = "mathbb", kind = "font", label = "\\mathbb{}", body = "\\mathbb{$1}",
    aliases = { "blackboard", "double struck", "reals", "naturals" }, doc = "amsfonts: blackboard bold capitals",
  },
  {
    cmd = "boldsymbol", kind = "font", label = "\\boldsymbol{}", body = "\\boldsymbol{$1}",
    aliases = { "bold", "vector" }, doc = "amsmath: bold italic symbols (works on Greek)",
  },
  {
    cmd = "pmb", kind = "font", label = "\\pmb{}", body = "\\pmb{$1}",
    aliases = { "poor man's bold" }, doc = "amsmath: poor man's bold (overprinted)",
  },
  {
    cmd = "text", kind = "font", label = "\\text{}", body = "\\text{$1}",
    aliases = { "words", "prose" }, doc = "amsmath: upright text inside math mode",
  },
  {
    cmd = "textbf", kind = "font", label = "\\textbf{}", body = "\\textbf{$1}",
    aliases = { "bold text" }, doc = "Bold text",
  },
  {
    cmd = "textit", kind = "font", label = "\\textit{}", body = "\\textit{$1}",
    aliases = { "italic text" }, doc = "Italic text",
  },

  -- kind: spacing ----------------------------------------------------------
  { cmd = ",", kind = "spacing", aliases = { "thin space" }, doc = "Thin space (3/18 quad)" },
  { cmd = ":", kind = "spacing", aliases = { "medium space" }, doc = "Medium space (4/18 quad)" },
  { cmd = ";", kind = "spacing", aliases = { "thick space" }, doc = "Thick space (5/18 quad)" },
  { cmd = "!", kind = "spacing", aliases = { "negative space" }, doc = "Negative thin space" },
  { cmd = "quad", kind = "spacing", doc = "One quad of horizontal space" },
  { cmd = "qquad", kind = "spacing", doc = "Two quads of horizontal space" },
  { cmd = "enspace", kind = "spacing", doc = "Half-quad of horizontal space" },
  {
    cmd = "hspace", kind = "spacing", label = "\\hspace{}", body = "\\hspace{$1}",
    aliases = { "space" }, doc = "Explicit horizontal space of a given length",
  },

  -- kind: environment ------------------------------------------------------
  {
    cmd = "cases", kind = "environment", label = "\\begin{cases}",
    body = "\\begin{cases}\n\t$1 & \\text{if } $2 \\\\\\\\\n\t$3 & \\text{otherwise}\n\\end{cases}",
    aliases = { "piecewise", "branch" }, doc = "amsmath: piecewise definition",
  },
  {
    cmd = "dcases", kind = "environment", label = "\\begin{dcases}",
    body = "\\begin{dcases}\n\t$1 & \\text{if } $2 \\\\\\\\\n\t$3 & \\text{otherwise}\n\\end{dcases}",
    aliases = { "piecewise", "display" }, doc = "mathtools: piecewise definition in display style",
  },
  {
    cmd = "rcases", kind = "environment", label = "\\begin{rcases}",
    body = "\\begin{rcases}\n\t$1 \\\\\\\\\n\t$2\n\\end{rcases}",
    aliases = { "piecewise", "right brace" }, doc = "mathtools: cases with the brace on the right",
  },
  {
    cmd = "align", kind = "environment", label = "\\begin{align}",
    body = "\\begin{align}\n\t$1 &= $2 \\\\\\\\\n\t&= $3\n\\end{align}",
    aliases = { "equations", "derivation" }, doc = "amsmath: aligned numbered equations",
  },
  {
    cmd = "align*", kind = "environment", label = "\\begin{align*}",
    body = "\\begin{align*}\n\t$1 &= $2 \\\\\\\\\n\t&= $3\n\\end{align*}",
    aliases = { "equations", "derivation", "unnumbered" }, doc = "amsmath: aligned unnumbered equations",
  },
  {
    cmd = "aligned", kind = "environment", label = "\\begin{aligned}",
    body = "\\begin{aligned}\n\t$1 &= $2 \\\\\\\\\n\t&= $3\n\\end{aligned}",
    aliases = { "equations", "inner" }, doc = "amsmath: alignment block usable inside another environment",
  },
  {
    cmd = "gather", kind = "environment", label = "\\begin{gather}",
    body = "\\begin{gather}\n\t$1 \\\\\\\\\n\t$2\n\\end{gather}",
    aliases = { "centred equations" }, doc = "amsmath: centred numbered equations",
  },
  {
    cmd = "gathered", kind = "environment", label = "\\begin{gathered}",
    body = "\\begin{gathered}\n\t$1 \\\\\\\\\n\t$2\n\\end{gathered}",
    aliases = { "centred equations", "inner" }, doc = "amsmath: gather block usable inside another environment",
  },
  {
    cmd = "split", kind = "environment", label = "\\begin{split}",
    body = "\\begin{split}\n\t$1 &= $2 \\\\\\\\\n\t&= $3\n\\end{split}",
    doc = "amsmath: split one numbered equation over several aligned lines",
  },
  {
    cmd = "multline", kind = "environment", label = "\\begin{multline}",
    body = "\\begin{multline}\n\t$1 \\\\\\\\\n\t$2\n\\end{multline}",
    aliases = { "long equation" }, doc = "amsmath: one long equation broken across lines",
  },
  {
    cmd = "multlined", kind = "environment", label = "\\begin{multlined}",
    body = "\\begin{multlined}\n\t$1 \\\\\\\\\n\t$2\n\\end{multlined}",
    aliases = { "long equation", "inner" }, doc = "mathtools: multline block usable inside another environment",
  },
  {
    cmd = "matrix", kind = "environment", label = "\\begin{matrix}",
    body = "\\begin{matrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{matrix}",
    aliases = { "matrix", "array" }, doc = "amsmath: matrix with no delimiters",
  },
  {
    cmd = "pmatrix", kind = "environment", label = "\\begin{pmatrix}",
    body = "\\begin{pmatrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{pmatrix}",
    aliases = { "matrix", "parentheses" }, doc = "amsmath: matrix delimited by ( )",
  },
  {
    cmd = "bmatrix", kind = "environment", label = "\\begin{bmatrix}",
    body = "\\begin{bmatrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{bmatrix}",
    aliases = { "matrix", "brackets" }, doc = "amsmath: matrix delimited by [ ]",
  },
  {
    cmd = "Bmatrix", kind = "environment", label = "\\begin{Bmatrix}",
    body = "\\begin{Bmatrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{Bmatrix}",
    aliases = { "matrix", "braces" }, doc = "amsmath: matrix delimited by { }",
  },
  {
    cmd = "vmatrix", kind = "environment", label = "\\begin{vmatrix}",
    body = "\\begin{vmatrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{vmatrix}",
    aliases = { "matrix", "determinant" }, doc = "amsmath: matrix delimited by | | (determinant)",
  },
  {
    cmd = "Vmatrix", kind = "environment", label = "\\begin{Vmatrix}",
    body = "\\begin{Vmatrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{Vmatrix}",
    aliases = { "matrix", "norm" }, doc = "amsmath: matrix delimited by || ||",
  },
  {
    cmd = "smallmatrix", kind = "environment", label = "\\begin{smallmatrix}",
    body = "\\begin{smallmatrix}\n\t$1 & $2 \\\\\\\\\n\t$3 & $4\n\\end{smallmatrix}",
    aliases = { "matrix", "inline" }, doc = "amsmath: inline-sized matrix",
  },
  {
    cmd = "array", kind = "environment", label = "\\begin{array}",
    body = "\\begin{array}{$1}\n\t$2\n\\end{array}",
    aliases = { "table", "matrix" }, doc = "Array with an explicit column specification",
  },
  {
    cmd = "equation", kind = "environment", label = "\\begin{equation}",
    body = "\\begin{equation}\n\t$1\n\\end{equation}",
    aliases = { "numbered" }, doc = "Numbered display equation",
  },
  {
    cmd = "equation*", kind = "environment", label = "\\begin{equation*}",
    body = "\\begin{equation*}\n\t$1\n\\end{equation*}",
    aliases = { "unnumbered" }, doc = "amsmath: unnumbered display equation",
  },

  -- kind: misc -------------------------------------------------------------
  { cmd = "dots", kind = "misc", glyph = "…", aliases = { "ellipsis" }, doc = "amsmath: context-sensitive ellipsis" },
  { cmd = "ldots", kind = "misc", glyph = "…", aliases = { "ellipsis" }, doc = "Low (baseline) ellipsis" },
  { cmd = "cdots", kind = "misc", glyph = "⋯", aliases = { "ellipsis" }, doc = "Centred ellipsis" },
  { cmd = "vdots", kind = "misc", glyph = "⋮", aliases = { "ellipsis" }, doc = "Vertical ellipsis" },
  { cmd = "ddots", kind = "misc", glyph = "⋱", aliases = { "ellipsis" }, doc = "Diagonal ellipsis" },
  { cmd = "dotsb", kind = "misc", glyph = "⋯", aliases = { "ellipsis" }, doc = "amsmath: ellipsis between operators" },
  { cmd = "dotsc", kind = "misc", glyph = "…", aliases = { "ellipsis" }, doc = "amsmath: ellipsis between commas" },
  { cmd = "prime", kind = "misc", glyph = "′", aliases = { "derivative" }, doc = "Prime" },
  { cmd = "backslash", kind = "misc", glyph = "\\", doc = "Backslash" },
  { cmd = "dagger", kind = "misc", glyph = "†", aliases = { "adjoint" }, doc = "Dagger" },
  { cmd = "ddagger", kind = "misc", glyph = "‡", doc = "Double dagger" },
  { cmd = "star", kind = "misc", glyph = "⋆", doc = "Star operator" },
  { cmd = "ast", kind = "misc", glyph = "∗", aliases = { "asterisk", "convolution" }, doc = "Asterisk operator" },
  { cmd = "circ", kind = "misc", glyph = "∘", aliases = { "compose" }, doc = "Ring operator (composition)" },
  { cmd = "bullet", kind = "misc", glyph = "•", doc = "Bullet operator" },
  { cmd = "surd", kind = "misc", glyph = "√", doc = "Radical sign (no vinculum)" },
  { cmd = "checkmark", kind = "misc", glyph = "✓", aliases = { "tick", "done" }, doc = "amssymb: check mark" },
  { cmd = "square", kind = "misc", glyph = "□", aliases = { "box", "qed" }, doc = "amssymb: white square" },
  { cmd = "blacksquare", kind = "misc", glyph = "■", aliases = { "qed", "end of proof" }, doc = "amssymb: black box" },
  { cmd = "triangle", kind = "misc", glyph = "△", doc = "White up-pointing triangle" },
  { cmd = "lozenge", kind = "misc", glyph = "◊", aliases = { "diamond" }, doc = "amssymb: lozenge" },
  { cmd = "blacklozenge", kind = "misc", glyph = "⧫", doc = "amssymb: black lozenge" },
  { cmd = "bigstar", kind = "misc", glyph = "★", doc = "amssymb: black star" },
  { cmd = "blacktriangle", kind = "misc", glyph = "▲", doc = "amssymb: black up-pointing triangle" },
  { cmd = "blacktriangledown", kind = "misc", glyph = "▼", doc = "amssymb: black down-pointing triangle" },
  { cmd = "blacktriangleleft", kind = "misc", glyph = "◀", doc = "amssymb: black left-pointing triangle" },
  { cmd = "blacktriangleright", kind = "misc", glyph = "▶", doc = "amssymb: black right-pointing triangle" },
  { cmd = "diagup", kind = "misc", glyph = "╱", doc = "amssymb: rising diagonal line" },
  { cmd = "diagdown", kind = "misc", glyph = "╲", doc = "amssymb: falling diagonal line" },
  { cmd = "flat", kind = "misc", glyph = "♭", doc = "Music flat sign" },
  { cmd = "natural", kind = "misc", glyph = "♮", doc = "Music natural sign" },
  { cmd = "sharp", kind = "misc", glyph = "♯", doc = "Music sharp sign" },
  { cmd = "clubsuit", kind = "misc", glyph = "♣", doc = "Club suit" },
  { cmd = "diamondsuit", kind = "misc", glyph = "♢", doc = "Diamond suit" },
  { cmd = "heartsuit", kind = "misc", glyph = "♡", doc = "Heart suit" },
  { cmd = "spadesuit", kind = "misc", glyph = "♠", doc = "Spade suit" },
  { cmd = "angle", kind = "misc", glyph = "∠", doc = "Angle" },
  { cmd = "measuredangle", kind = "misc", glyph = "∡", doc = "amssymb: measured angle" },
  { cmd = "sphericalangle", kind = "misc", glyph = "∢", doc = "amssymb: spherical angle" },
  { cmd = "forall", kind = "misc", glyph = "∀", aliases = { "for all", "universal" }, doc = "Universal quantifier" },
  { cmd = "exists", kind = "misc", glyph = "∃", aliases = { "there exists" }, doc = "Existential quantifier" },
  { cmd = "nexists", kind = "misc", glyph = "∄", aliases = { "there is no" }, doc = "amssymb: there does not exist" },
  { cmd = "neg", kind = "misc", glyph = "¬", aliases = { "not", "negation" }, doc = "Logical not" },
  { cmd = "lnot", kind = "misc", glyph = "¬", aliases = { "not", "negation" }, doc = "Logical not" },
  { cmd = "top", kind = "misc", glyph = "⊤", aliases = { "true", "verum" }, doc = "Top / true" },
  { cmd = "bot", kind = "misc", glyph = "⊥", aliases = { "false", "falsum" }, doc = "Bottom / false" },
  { cmd = "vdash", kind = "misc", glyph = "⊢", aliases = { "proves", "turnstile" }, doc = "Right tack (proves)" },
  { cmd = "dashv", kind = "misc", glyph = "⊣", doc = "Left tack" },
  { cmd = "models", kind = "misc", glyph = "⊨", aliases = { "satisfies" }, doc = "Double turnstile (models)" },
  { cmd = "vDash", kind = "misc", glyph = "⊨", aliases = { "entails" }, doc = "amssymb: true (double turnstile)" },
  { cmd = "Vdash", kind = "misc", glyph = "⊩", aliases = { "forces" }, doc = "amssymb: forces" },
  { cmd = "nvdash", kind = "misc", glyph = "⊬", doc = "amssymb: does not prove" },
  { cmd = "therefore", kind = "misc", glyph = "∴", doc = "amssymb: therefore" },
  { cmd = "because", kind = "misc", glyph = "∵", doc = "amssymb: because" },
  { cmd = "%", kind = "misc", glyph = "%", aliases = { "percent" }, doc = "Literal percent sign" },
  { cmd = "#", kind = "misc", glyph = "#", aliases = { "hash", "number sign" }, doc = "Literal hash sign" },
  { cmd = "&", kind = "misc", glyph = "&", aliases = { "ampersand" }, doc = "Literal ampersand" },
  { cmd = "_", kind = "misc", glyph = "_", aliases = { "underscore" }, doc = "Literal underscore" },
}
