local config = require("andrew.vault.config")
local ui = require("andrew.vault.ui")

local M = {}

--- Display a floating window with advanced search syntax reference.
function M.search_help()
  local lines = {
    "Advanced Search Syntax",
    "======================",
    "",
    "Text Search (ripgrep):",
    "  deploy                   Files containing \"deploy\"",
    "  \"exact phrase\"           Quoted exact match",
    "  /^## Results/            Regex pattern",
    "  /pattern/i               Case-insensitive regex",
    "  /pattern/m               Multiline regex",
    "  /pattern/s               Dotall (. matches newline)",
    "",
    "Field Filters (field:value):",
    "  type:meeting             Frontmatter type",
    "  tag:project/active       Has tag (or child)",
    "  tag:project,-archived    Exclude archived subtree",
    "  tag:project,-a,-b        Multiple exclusions",
    "  path:Projects/           File path prefix",
    "  file:Dashboard           Basename substring",
    "  folder:Projects/Alpha    Folder prefix",
    "  status:active            Status field",
    "  priority:>3              Numeric comparison",
    "  priority:1..3            Numeric range",
    "",
    "Date Filters:",
    "  modified:<7d             Less than 7 days ago",
    "  modified:>30d            More than 30 days ago",
    "  modified:last-7d         Within last 7 days",
    "  modified:today           Modified today",
    "  modified:this-week       Since Monday",
    "  modified:this-month      Since 1st of month",
    "  created:2026-01-15       Exact date",
    "  created:2026-01..2026-02 Date range",
    "",
    "Task Filters:",
    "  task:\"\"                  Any task",
    "  task-todo:\"\"             Open tasks",
    "  task-done:\"\"             Completed tasks",
    "  task-due:<today          Overdue tasks",
    "  task-due:this-week       Tasks due this week",
    "  task-due:<7d             Due within 7 days",
    "  task-priority:1          Priority 1 tasks",
    "  task-priority:<=2        High priority (1-2)",
    "  task-priority:1..3       Priority range",
    "  task-tag:urgent          Tasks tagged #urgent",
    "  task-state:in-progress   In-progress tasks",
    "  task-repeat:\"\"           Recurring tasks",
    "  task-completion:<7d      Recently completed",
    "  has:tasks                Files with tasks",
    "",
    "Link Filters:",
    "  links-to:NoteName        Notes linking to NoteName",
    "  links-to:Note#Heading    Notes linking to specific heading",
    '  links-to:"Project Alpha" Quote names with spaces',
    "  linked-from:NoteName     Notes that NoteName links to",
    "  linked-from:Note#Heading Notes linked from a section",
    "  alias:CFD                Notes with specific alias",
    "",
    "Existence Checks:",
    "  has:tags                 Files with tags",
    "  has:aliases              Files with aliases",
    "  has:outlinks             Files with links",
    "  has:inlinks              Files linked to",
    "  has:frontmatter          Files with frontmatter",
    "",
    "Graph Traversal:",
    "  graph:depth=2            Notes within 2 hops of current",
    "  graph:depth=3,dir=forward  3 hops, outlinks only",
    "  graph:depth=2,dir=backward 2 hops, inlinks only",
    "  graph:neighbors          Shorthand for depth=1",
    "  graph:extended           Shorthand for depth=2",
    "  graph:depth=2 tag:active Combine with other filters",
    "",
    "Boolean Operators:",
    "  AND / OR / NOT           Explicit operators",
    "  -tag:archived            Shorthand for NOT",
    "  (a OR b) AND c           Grouping with parens",
    "",
    "Implicit AND:",
    "  type:meeting tag:urgent  = type:meeting AND tag:urgent",
    "",
    "Precedence: NOT > AND > OR",
    "",
    "Result Grouping:",
    "  group:folder             Group by parent folder",
    "  group:type               Group by frontmatter type",
    "  group:tag                Group by top-level tag",
    "  group:date               Group by modification date",
    "  group:month              Group by modification month",
    "  group:created            Group by creation date",
    "  group:status             Group by status field",
    "",
    "Press q or <Esc> to close",
  }

  ui.create_float_display({
    title = "Search Help",
    lines = lines,
    width = config.search.help_width,
    height = #lines,
    filetype = "markdown",
  })
end

return M
