-- Spec for the two generators, snippets/gen-mpi.lua and snippets/gen-omp.lua.
--
-- WHAT IT PINS
--
-- The generated tables are committed, not built at startup: `mpi.mod` is
-- gzip'd gfortran module format 15, coupled to this exact Open MPI and gfortran
-- pair, and nothing may parse it on a hover. The cost of committing output is
-- that it can go stale silently -- someone edits `snippets/overrides/mpi.lua`,
-- forgets to re-run the generator, and the repository now claims a `standard`
-- nobody can see. This spec re-runs each generator into a temp directory and
-- compares BYTES with the committed file, which catches both staleness and any
-- loss of idempotence in the serializer (unsorted keys, a timestamp in `_meta`,
-- hash-ordered inner tables -- the exact defect `extract-docs.lua` still has).
--
-- It SKIPS, loudly, when the machine source is absent, so the suite stays green
-- on a box with no Open MPI or no gfortran. A skip is counted as a pass on
-- purpose: a machine that cannot regenerate cannot say anything about freshness,
-- and failing there would train people to ignore the suite.
--
-- Discriminating power (each verified by reintroducing the bug):
--   * "data/mpi.lua is current" fails if the committed file is stale, if the
--     serializer stops sorting keys at any level, or if `_meta` gains a
--     timestamp.
--   * "data/openmp.lua is current" fails the same way for the OpenMP half.
--   * "--out is honoured" fails if a generator ignores the flag and writes into
--     the repository -- which would make this spec silently rewrite the file it
--     is supposed to be checking.
--   * "an override may not carry a machine-owned key" fails if a generator goes
--     back to merely DECLINING to overwrite `interface`/`signature`/
--     `result_type`/`value`. Declining is not enough: on an entry the compiler
--     has no such value for -- every constant has no `interface` -- an override
--     carrying one used to be INJECTED whole, and every inlay hint and
--     signature-help offset downstream would then be built from a dummy list no
--     `.mod` ever vouched for. Both the inject case (a constant) and the
--     overwrite case (a procedure) are exercised, on both generators.
--   * "a module entry may still carry a signature" fails if the guard is
--     widened to every kind: `mpi_f08` and the OpenMP clauses are syntax, not
--     library symbols, and their `signature` has no machine source to come
--     from. It is the test that stops the fix turning into a regression.
--   * "--overrides-dir reproduces the committed bytes" fails if a generator
--     stops going through snippets/fortran-overrides.lua -- the one door onto
--     the hand-authored tables -- or if the flag is read but not honoured,
--     which would make the guard tests above vacuous.
--
-- Run with: nvim --headless -u NONE -l tests/fortran_registry_fresh_spec.lua

local _H = dofile((debug.getinfo(1, "S").source:gsub("^@", "")):match("^(.*)[/\\]") .. "/spec_helper.lua")
local test, assert_eq, assert_true = _H.test, _H.assert_eq, _H.assert_true

package.path = vim.fn.stdpath("config") .. "/lua/?.lua;" .. package.path

local root = vim.fn.stdpath("config")

---@param path string
---@return string|nil
local function read(path)
  local fh = io.open(path, "rb")
  if not fh then
    return nil
  end
  local s = fh:read("*a")
  fh:close()
  return s
end

--- Is the machine source this generator needs present?
local function have_mpi_mod()
  return vim.fn.filereadable(vim.fn.expand("~/miniconda3/include/mpi.mod")) == 1
end

local function have_omp_lib()
  local out = vim.fn.system({ "gfortran", "-print-file-name=finclude" })
  if vim.v.shell_error ~= 0 then
    return false
  end
  return vim.fn.filereadable(vim.trim(out) .. "/omp_lib.f90") == 1
end

--- Run one generator into `dir`; return the regenerated bytes.
---@param script string
---@param out string
---@param name string
---@return string|nil bytes, string log
local function regenerate(script, out, name)
  local cmd = {
    vim.v.progpath, "--headless", "-u", "NONE", "-l", root .. "/snippets/" .. script,
    "--out", out,
  }
  local log = vim.fn.system(cmd)
  return read(out .. "/" .. name .. ".lua"), log
end

---@param got string|nil
---@param want string|nil
---@param label string
local function assert_same_bytes(got, want, label)
  assert_true(want ~= nil, label .. ": the committed file exists")
  assert_true(got ~= nil, label .. ": the generator produced output")
  if got == want then
    assert_eq(#got, #want, label .. " byte length:")
    return
  end
  -- report the first differing line, not 500 kB of diff
  local gl = vim.split(got, "\n", { plain = true })
  local wl = vim.split(want, "\n", { plain = true })
  for i = 1, math.max(#gl, #wl) do
    if gl[i] ~= wl[i] then
      error(("%s differs at line %d\n  committed: %s\n  generated: %s")
        :format(label, i, vim.inspect(wl[i]), vim.inspect(gl[i])))
    end
  end
  error(label .. " differs in length only: " .. #want .. " vs " .. #got)
end

local tmp = vim.fn.tempname()
vim.fn.mkdir(tmp, "p")

test("data/mpi.lua is byte-identical to a fresh run of gen-mpi.lua", function()
  if not have_mpi_mod() then
    print("    SKIP: ~/miniconda3/include/mpi.mod is absent (no Open MPI on this box)")
    return
  end
  local got, log = regenerate("gen-mpi.lua", tmp, "mpi")
  assert_true(got ~= nil, "gen-mpi.lua produced no output; log: " .. tostring(log))
  assert_same_bytes(got, read(root .. "/lua/andrew/fortran/data/mpi.lua"), "data/mpi.lua")
end)

test("data/openmp.lua is byte-identical to a fresh run of gen-omp.lua", function()
  if not have_omp_lib() then
    print("    SKIP: omp_lib.f90 is absent (no gfortran finclude on this box)")
    return
  end
  local got, log = regenerate("gen-omp.lua", tmp, "openmp")
  assert_true(got ~= nil, "gen-omp.lua produced no output; log: " .. tostring(log))
  assert_same_bytes(got, read(root .. "/lua/andrew/fortran/data/openmp.lua"), "data/openmp.lua")
end)

test("--out keeps a generator out of the repository", function()
  if not have_mpi_mod() then
    print("    SKIP: ~/miniconda3/include/mpi.mod is absent")
    return
  end
  local marker = root .. "/lua/andrew/fortran/data/mpi.lua"
  local before = vim.fn.getftime(marker)
  local other = vim.fn.tempname()
  vim.fn.mkdir(other, "p")
  regenerate("gen-mpi.lua", other, "mpi")
  assert_true(vim.fn.filereadable(other .. "/mpi.lua") == 1, "wrote to the temp dir:")
  assert_eq(vim.fn.getftime(marker), before, "did not touch the committed file:")
  vim.fn.delete(other, "rf")
end)

--- Run a generator with a hand-made overrides directory; return exit code + log.
---@param script string
---@param name string `"mpi"` or `"openmp"`
---@param body string Lua source of the override table
---@return integer code, string log, boolean wrote
local function run_with_overrides(script, name, body)
  local odir = vim.fn.tempname()
  local out = vim.fn.tempname()
  vim.fn.mkdir(odir, "p")
  vim.fn.mkdir(out, "p")
  local fh = assert(io.open(odir .. "/" .. name .. ".lua", "w"))
  fh:write(body)
  fh:close()
  local log = vim.fn.system({
    vim.v.progpath, "--headless", "-u", "NONE", "-l", root .. "/snippets/" .. script,
    "--out", out, "--overrides-dir", odir,
  })
  local code = vim.v.shell_error
  local wrote = vim.fn.filereadable(out .. "/" .. name .. ".lua") == 1
  vim.fn.delete(odir, "rf")
  vim.fn.delete(out, "rf")
  return code, log, wrote
end

test("gen-mpi refuses an override that carries a machine-owned key", function()
  if not have_mpi_mod() then
    print("    SKIP: ~/miniconda3/include/mpi.mod is absent")
    return
  end

  -- The inject case. `mpi_comm_world` is a constant, so it has no `interface`
  -- for the old "do not overwrite what exists" rule to protect -- this table
  -- used to sail straight through and land in the committed data.
  local code, log, wrote = run_with_overrides("gen-mpi.lua", "mpi", [[
return {
  mpi_comm_world = {
    interface = { { name = "not_a_dummy", type = "integer", intent = "in" } },
  },
}
]])
  assert_true(code ~= 0, "injecting `interface` on a constant is fatal; log: " .. log)
  assert_true(log:find("interface", 1, true) ~= nil, "and says which key: " .. log)
  assert_true(not wrote, "and writes nothing:")

  -- The overwrite case, on a procedure the compiler fully describes.
  code, log, wrote = run_with_overrides("gen-mpi.lua", "mpi", [[
return { mpi_comm_rank = { signature = "MPI_Comm_rank(comm, ierr)" } }
]])
  assert_true(code ~= 0, "overwriting `signature` on a subroutine is fatal; log: " .. log)
  assert_true(log:find("signature", 1, true) ~= nil, "and says which key: " .. log)
  assert_true(not wrote, "and writes nothing:")
end)

test("gen-omp refuses an override that carries a machine-owned key", function()
  if not have_omp_lib() then
    print("    SKIP: omp_lib.f90 is absent")
    return
  end
  local code, log, wrote = run_with_overrides("gen-omp.lua", "openmp", [[
return { omp_get_wtime = { result_type = "integer" } }
]])
  assert_true(code ~= 0, "`result_type` on a function is fatal; log: " .. log)
  assert_true(log:find("result_type", 1, true) ~= nil, "and says which key: " .. log)
  assert_true(not wrote, "and writes nothing:")

  code, log, wrote = run_with_overrides("gen-omp.lua", "openmp", [[
return { omp_get_wtime = { interface = { { name = "x", type = "integer" } } } }
]])
  assert_true(code ~= 0, "`interface` on a function is fatal; log: " .. log)
  assert_true(not wrote, "and writes nothing:")
end)

test("a directive, clause or module may still carry a signature", function()
  if not have_omp_lib() then
    print("    SKIP: omp_lib.f90 is absent")
    return
  end
  -- `PRIVATE(list)` has no compiler record anywhere; the override IS its only
  -- source. The guard must fire on kind, not on the key alone.
  local code, log, wrote = run_with_overrides("gen-omp.lua", "openmp", [[
return {
  private = { name = "PRIVATE", kind = "clause", signature = "PRIVATE(list)",
    summary = "Give each thread its own uninitialized copy" },
}
]])
  assert_eq(code, 0, "a clause's own signature is accepted; log: " .. log)
  assert_true(wrote, "and the table is written:")
end)

test("--overrides-dir reproduces the committed bytes", function()
  if not have_mpi_mod() then
    print("    SKIP: ~/miniconda3/include/mpi.mod is absent")
    return
  end
  -- Pointing the flag at the real directory must be indistinguishable from
  -- omitting it: that is what proves the flag is honoured (so the guard tests
  -- above are not vacuous) AND that the generator reads its overrides through
  -- snippets/fortran-overrides.lua rather than by its own path arithmetic.
  local out = vim.fn.tempname()
  vim.fn.mkdir(out, "p")
  local log = vim.fn.system({
    vim.v.progpath, "--headless", "-u", "NONE", "-l", root .. "/snippets/gen-mpi.lua",
    "--out", out, "--overrides-dir", root .. "/snippets/overrides",
  })
  assert_same_bytes(read(out .. "/mpi.lua"), read(root .. "/lua/andrew/fortran/data/mpi.lua"),
    "gen-mpi.lua --overrides-dir snippets/overrides" .. (log ~= "" and ("; log: " .. log) or ""))
  vim.fn.delete(out, "rf")
end)

test("regenerating twice produces the same bytes", function()
  if not have_omp_lib() then
    print("    SKIP: omp_lib.f90 is absent")
    return
  end
  local a = regenerate("gen-omp.lua", tmp, "openmp")
  local b = regenerate("gen-omp.lua", tmp, "openmp")
  assert_same_bytes(b, a, "gen-omp.lua run twice")
end)

vim.fn.delete(tmp, "rf")

_H.finish()
